### ISSUE TITLE
v1.7.0 not on GitHub

### ISSUE THREAD

**Issue by thephpjedi** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#10]
No v1.7.0 tag exists on GitHub, nor any branch or commit that seems related to v1.7.0 announced in http://steamcommunity.com/sharedfiles/filedetails/changelog/583429740

Seems most releases are not tagged on GitHub; that would be useful to see code at that specific release.

I'd like to investigate a bug related to train spawning/despawning at map edges.

**Comment by VictorPhilipp** [comment]
This bug has been fixed in 1.7.1

**Comment by thephpjedi** [comment]
@VictorPhilipp: Thanks for bugfix and info. Happy to help contribute if regular development is made in this repo. :)

**Comment by VictorPhilipp** [comment]
I better should! :+1:
