### ISSUE TITLE
CSUtil.Common files has no version number (was: No menu button in 1.10.5)

### ISSUE THREAD

**Issue by penma** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#104]
This issue refers to the Steam workshop version

Since update to 1.10.5, the menu button is gone. Resetting configuration from options window doesn't change anything. This issue affects savegames from 1.10.4 as well as freshly started games.

The following message appears twice in output.log (at the end, after most of the other level loading) and is probably related: `MissingMethodException: Method not found: 'CSUtil.Commons.VectorUtil.ClampRectToScreen'.`

**Comment by penma** [comment]
Issue was a local build of TM 1.10.4 which was installed but deactivated. Since C:S does not isolate mods properly and loads assemblies from an arbitrary location (in this case, local mod dir instead of preferring - or only even allowing - the directory of the mod), picked an outdated version, which lacked the method.

CSUtil.Common in both versions have a file version of 1.0.0.0, requesting an assembly at least a certain version (= first version where this function was introduced) might have avoided that issue.

Other than that, the issue as originally described is PEBKAC

**Comment by VictorPhilipp** [comment]
Sorry, I thought that version numbers increment automatically on build.

**Comment by penma** [comment]
Yes, when specifying `[assembly: AssemblyVersion("1.0.*")]` in AssemlyInfo.cs (like done for TMPE itself) instead of 1.0.0.0 :-)
