### ISSUE TITLE
Add multiple pedestrian traffic lights for roads with multiple pedestrian lanes

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#105]
@t1a2l: "Can you add seperate pedestrian traffic lights for different sides of big roads? like 4 lanes and up (ofcourse there should be a madian in the middle)."

**Comment by t1a2l** [comment]
Thanks, I'm not sure I explanied myself correctly.

**Comment by t1a2l** [comment]
Hey, is there any ETA on this feature?

**Comment by VictorPhilipp** [comment]
moved
