### ISSUE TITLE
Says incompatible with another mod

### ISSUE THREAD

**Issue by krj7709** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#11]
Says that with my other mods and without them. Even tried removing all mods except this one from the directory and get same result. Only thing that seems to work is toggling the traffic lights. Any ideas? Tried downloading the source and recompiling but my virtual studio always has errors. And visual studio can't load the tmf playground? Required for building?

**Comment by krj7709** [comment]
Can you give me a link to an older version to try. Unsure why this mod won't work. Running snowfall.

**Comment by VictorPhilipp** [comment]
I also don't know why it is not working for you. Do you have got a player_log.txt and TMPE.log on your hand?

**Comment by krj7709** [comment]
Its is working now. Don't know what was going on. Keep up the good work.
