### ISSUE TITLE
Option to replace Green with Yield on Timed traffic lights

### ISSUE THREAD

**Issue by adiac** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#112]
In my hometown in Germany there are some Traffic lights that don't even have a green phase. The lights turn from red to yellow and then off, thus cars need to follow yield rules.

-This feature can be useful for small roads with really low traffic.
-Also this could be used to make more realistic turns at signals without a separate phase for cars turning left.
-Together with my other request for "Day/Night Settings for Timed traffic lights" you could set traffic lights to shut down at night.

To implement this I would add a fourth signal (Traffic lights off or yellow flashing)
In this phase the traffic will obey the separate set yield rules of the intersection.

Thanks for reading this suggestion, I hope you find the idea interesting.

http://steamcommunity.com/workshop/filedetails/discussion/583429740/1697167355215994053/

**Comment by VictorPhilipp** [comment]
https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/26
