### ISSUE TITLE
Day/Night Settings for Timed traffic lights (for Rush Hour mod)

### ISSUE THREAD

**Issue by adiac** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#113]
In some occasions it would be really great to have two or even more separate sequences:
-Night
-Morning Rush Hour
-Evening Rush Hour
-Saturdays (shopping time)
-Sundays (almost no traffic)

-At night/sundays traffic lights are often not even needed, thus just turning them off and switching over to yield rules would be great for traffic flow. (see my other suggestion "Option to replace Green with Yield on Timed traffic lights")
-In the morning traffic flow is increased in the direction of workplaces
-In the evening it is about the other way around.

Optimized traffic lights for each scenario would increase traffic flow, make traffic lights more realistic and also offer a challenge to get the most out of your intersections.
(I know traffic lights in TM:PE are already very smart, but this would give you even more control.)

This feature makes only sense to use if the Rush Hour mod is also used.
Implementation would be easy. Add two or more tabs at the top of the Timed traffic lights window and switch between them as the day/night cycle changes. The time should adapt to the settings set in the Rush Hour mod.

Thanks for reading this suggestion, I hope you find the idea interesting.

http://steamcommunity.com/workshop/filedetails/discussion/583429740/1697167355215993968/

**Comment by VictorPhilipp** [comment]
Related to https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/26
