### ISSUE TITLE
Remove crosswalk texture when pedestrians are restricted.

### ISSUE THREAD

**Issue by Sipke82** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#119]
Remove crosswalk texture when pedestrians are restricted.

As described here: https://www.reddit.com/r/CitiesSkylines/comments/50zcx4/mod_idea_tmpe_pedestrian_crossing_control_with/

**Comment by VictorPhilipp** [comment]
already referenced here:
https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/16

I am not an expert in making textures so someone else would have to do this.
