### ISSUE TITLE
improve realism of pedestrians

### ISSUE THREAD

**Issue by Sipke82** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#120]
in my opinion, cim's walk way too far and way too fast. In order to make things more realistic perhaps we could do the following:
- Decrease walking speed to 50%?
- Decreasing maximum walking distance?
- Add (more) pathfinding costs to walking?

**Comment by DaEgi01** [comment]
I am of the same opinion but IMO max speed is not something "TM:PE" should handle.
We have "Advanced Vehicle Options" to change the max speed for various vehicles.
We need an upgrade of AVO or another very similar mod for citizens.
