### ISSUE TITLE
Improve persistency of lane connections, speed limits, vehicle restrictions

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#122]
Monarch:
"Would it be possible to make the Lane connector persistent when using road upgrade tool to a road with same number of connection points and/or using the "Zoning toolset (toggle + upgrade tool)" mod to toggle zoning?

Also if Parking/Vehicle restrictions and Speed limits could be persistent it would be nice!"

**Comment by aubergine10** [comment]
If it's not possible to make it consistent, could some sort of visual cue (or sound?) be provided to let user know the action they are about to take (eg. upgrade road) will have impact on the TM:PE config for the segment or junction?

**Comment by VictorPhilipp** [comment]
moved
