### ISSUE TITLE
Cargoload of trains/trucks

### ISSUE THREAD

**Issue by Sipke82** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#123]
- Fix that cargo trains drive with around with really low loads of cargo. (1 - 30 %)
- Automatically select appropriate vehicle for load --> a van for a small load, a truck for a large load. (i've made difference in capacity in AVO, sadly i get trucks loaded for 50%, instead of a van, loaded for 100%), while vans would probably mean faster delivery.

**Comment by VictorPhilipp** [comment]
moved
