### ISSUE TITLE
Default speed limits set at Roads from Network Extensions 2 are not saved, when reloading the savegame

### ISSUE THREAD

**Issue by Sipke82** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#125]
Default speed limits set at Roads from Network Extensions 2 are not saved, when reloading the savegame.

**Comment by VictorPhilipp** [comment]
Works for me. Could you please provide steps to reproduce this issue?

**Comment by Sipke82** [comment]
I tested now after the parkflie update. Seems to be working for me now too. This is closed.
