### ISSUE TITLE
Add a Despawn all parked vehicles button

### ISSUE THREAD

**Issue by Sipke82** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#126]
Add a Despawn all parked vehicles button

**Comment by aubergine10** [comment]
Rather than adding extra button, what about keyboard modifiers?

* Click = despawn driving (current functionality)
* Alt+Click = despawn parked
* Ctrl+Click = despawn both

Modifiers could be explained in the button tooltip.

**Comment by aubergine10** [comment]
Added as button on `mod option > maint tab` in 1.10.8 release - close issue?

**Comment by Sipke82** [comment]
Good enough for me. Close seems fine

**Comment by aubergine10** [comment]
I can't close this issue
