### ISSUE TITLE
Speed limit signs window too big

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#128]
I'm running on smaller screen res than usual (1344x756) to boost fps a little, and the window with all the speed signs (when using lane speed tool) is taking up a huge amount of space.

Would it be possible to get an option to reduce the icon size on that window by 50%?

**Comment by aubergine10** [comment]
If small UI option is enabled for speeds window, the buttons/checkboxes/etc could be hidden to make it even smaller. (By time a user enables such a mod option, they already know about Shift and Ctrl modifier keys so no need for all that extra stuff in the condensed UI).

See also: #131 - default settings handled via Routes info view panel (so no need for that button on the main speed changer UI).

**Comment by VictorPhilipp** [comment]
moved
