### ISSUE TITLE
Vanilla traffic lights and level crossings being ignored

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#129]
In many areas of my city, road vehicles are ignoring traffic lights and level crossings.

At junctions with traffic lights, vehicles generally behave as if there were no traffic lights. On occasion, however, they obey the lights - but only for a short while.

At level crossings, both road and rail vehicles are behaving as if it's a road junction with Stop signs at all four entrances, with all the vehicles vying to get across the junction under their own guidance. Road vehicles, for the most part, are completely ignoring the closed crossing barriers - they just drive straight through them, and even through the train if it happens to be crossing at that moment in time. The train will sometimes "give way" to the cars, often resulting in it getting stuck, confused and then despawning.

For reference, I'm mostly using [UK Roads](https://steamcommunity.com/sharedfiles/filedetails/?id=1306733086) workshop assets, although I'm seeing similar behaviour on vanilla roads too. Similarly, I mostly use workshop train stations ([example](https://steamcommunity.com/sharedfiles/filedetails/?id=1295676106&searchtext=4+station)) and tracks ([example](https://steamcommunity.com/sharedfiles/filedetails/?id=1178802767&searchtext=)) although issues seem to occur with vanilla stations and tracks too.

I'm wondering if this is something to do with [Simulation Accuracy](https://www.viathinksoft.de/tmpe/wiki/index.php?title=Options#Simulation_accuracy) but the wiki doesn't really explain much about side-effects of that setting. My computer is ancient so I've got it set to "Low" but last night tried "Medium" but with same results.

**Comment by aubergine10** [comment]
I turned on the TM:PE "priority and yield signs" feature and the traffic lights and level crossings started working as expected. Looks like there's a glitch when that feature is turned off.

**Comment by VictorPhilipp** [comment]
The bug occurs when the timed traffic light feature is disabled. I think the priority sign feature is not involved.
