### ISSUE TITLE
Interface goes 'weird' in Linux

### ISSUE THREAD

**Issue by CRCinAU** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#13]
See Screenshot.

![20160821133800_1](https://cloud.githubusercontent.com/assets/3992884/17835219/1a3ad2ac-67a5-11e6-9516-784d7f9ac08a.jpg)

**Comment by CRCinAU** [comment]
![20160821135310_1](https://cloud.githubusercontent.com/assets/3992884/17835253/d7f55b2c-67a6-11e6-86fd-e3de628e2aeb.jpg)
![20160821135324_1](https://cloud.githubusercontent.com/assets/3992884/17835254/d7f67e30-67a6-11e6-8f4b-7ce2b984f3cd.jpg)

**Comment by CRCinAU** [comment]
Most other elements are sized and drawn correctly.

**Comment by VictorPhilipp** [comment]
Are you using a dual monitor setup?

**Comment by CRCinAU** [comment]
Yes. I have 3 x screens @ 1920x1080. C:S runs at 1920x1080 on the primary screen.

**Comment by VictorPhilipp** [comment]
Fixed in 1.7.9
