### ISSUE TITLE
Sync level crossing barriers if road segment has crossing at both ends

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#130]
Vanilla behaviour is like this:

```
...|+|...|+|...
```

Where:

* `...` - one or more road segments
* `|` - signs and barriers at crossing-end of a road segment
* `+` - level crossing

There is a situation, however, where there will only be a single road segment between two level crossings ([particularly with 4 platform stations](https://steamcommunity.com/sharedfiles/filedetails/?id=1295676106&searchtext=4+station)):

```
...|+|_|+|...
```
Where `_` is a single road segment.

In this specific situation, where road segment has level crossing at both ends:

* Remove the signs/barriers from the middle segment (result: `...|+_+|...`)
* Treat outer segment barriers as if they are part of the same crossing (as if it was like this: `...|++|...`)
* Train using either track causes combined crossing to close to road traffic

That would drastically improve these "two doubletrack" crossings (currently each crossing is independent, resulting in traffic getting stuck on middle road segment).

EDIT: Middle segment length would likely need to be checked - eg. if it's a long segment, then probably better to retain vanilla functionality. It's only when short segment (eg. 4u or less) that the sign/barrier consolidation would take place.

**Comment by aubergine10** [comment]
The save linked in #140 includes an example (4 line train station) of the level crossing setup mentioned above.

**Comment by VictorPhilipp** [comment]
Sadly, this can only be fixed by CO.
