### ISSUE TITLE
Button to mark a road segment as blocked

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#133]
Useful for disaster planning. Ability to mark segments (and nodes?) as blocked to see what effect it has on traffic so I can adapt my road network accordingly.

The button would also allow me to unblock roads that the game created (eg. due to fire or #132).

**Comment by aubergine10** [comment]
Win extra internets if it adds traffic barrier or some other prop(s) —eg. traffic cones or something— to the segment whilst blocked.

**Comment by VictorPhilipp** [comment]
moved
