### ISSUE TITLE
Test "Old Town" Policy

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#134]
Just spotted this in Park Life release notes:

> Fixed: All traffic use Bus & Taxi lane when Old Town policy is active

I've never used that policy myself, but just flagging it up as something to test as vanilla code change will need carrying across to TM:PE.

**Comment by VictorPhilipp** [comment]
I believe the "Old Town" policy should work as expected but I have not tested it yet in the most recent version.

**Comment by VictorPhilipp** [comment]
moved
