### ISSUE TITLE
Wait to fill trains more

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#136]
Phoenix C64 says:
"I know this mod is more about traffic related to roads... but I know it also affects trains to some degree as I had to turn off TMPE at one point because it was affecting my trains in some bad way. (spend 3h. trouble shooting the problem and disabling TMPE fixed the issue)

Now, I currently have a big complaint about trains: trains only take 1-2 cargo trucks as a load and bottleneck my train network with 7-13% filled trains.

Could TMPE have an option so trains don't spawn until they have an X% of load (let's say 50%)"

**Comment by Sipke82** [comment]
Quite some times i observe the same effect with cargo ships and trucks (especially when i upgraded the capacity of trucks using AVO :-))

**Comment by aubergine10** [comment]
From a related issue: #123 

> 1. Fix that cargo trains drive with around with really low loads of cargo. (1 - 30 %)
> 2. Automatically select appropriate vehicle for load --> a van for a small load, a truck for a large load. (i've made difference in capacity in AVO, sadly i get trucks loaded for 50%, instead of a van, loaded for 100%), while vans would probably mean faster delivery.

**Comment by VictorPhilipp** [comment]
moved
