### ISSUE TITLE
No cims are spawning with TM:PE installed

### ISSUE THREAD

**Issue by haraldschioberg** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#14]
When TM:PE is installed (and all other mods disabled) no cims are appearing in a new city. All residences always have 0/x households, nobody has any workers, .... 

![tmpe bug](https://cloud.githubusercontent.com/assets/13667138/17878915/fc493d3e-68a2-11e6-96c9-c80e8e5be486.png)

**Comment by VictorPhilipp** [comment]
I uploaded a hotfix. Thanks for reporting!
