### ISSUE TITLE
Junction restrictions for pedestrian crossings are sometimes not preserved

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#142]
The state of the pedestrian crossing is not correctly saved/loaded on outgoing one-way roads.

**Comment by aubergine10** [comment]
You can see the bug in action on that savegame I uploaded for #140 (near the train station, there's a "squareabout" with skyscraper residences in the middle.
