### ISSUE TITLE
Traffic lights on 2+2 National highway cannot be enabled

### ISSUE THREAD

**Issue by Sipke82** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#149]
Traffic lights on 2+2 National highway cannot be enabled. could this be fixed?

**Comment by VictorPhilipp** [comment]
The bug occurs when you create a junction between 2+2 lane national roads.

**Comment by Sipke82** [comment]
I've reported on the workshop page of NeXT2 as well... not sure who should fix this?

**Comment by VictorPhilipp** [comment]
That is a bug in TMPE :) As you can see I have already tagged this issue with the "bug" label

**Comment by Sipke82** [comment]
All right, then you might want to know that the asymmetrical 2+1 national road is also affected.

**Comment by VictorPhilipp** [comment]
I was mistaken, this is not a bug in TMPE. Further investigations showed that toggling traffic lights indeed works for them (both the `CustomTrafficLights` and `TrafficLights` flags are set) but as @aubergine10 already guessed there is a problem with actually rendering the traffic light prop. This is not a bug in TMPE and thus cannot be fixed here. You should get in contact with the creators of NeXT2.
