### ISSUE TITLE
Keyboard shortcuts for tool selection, Copy-Paste, etc.

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#153]
If possible, add configurable keyboard shortcuts for copy-paste of traffic lights (and, when applicable, lane connections, vehicle restrictions and so on). Also, having shortcuts to select a sub-tool (eg. lane connector, vehicle restrictor, etc) would also be useful.

The shortcuts would only be active while TM:PE menu is active, or whilst relevant sub-tool is active, etc.

Shortcuts should ideally be configurable in mod options.

Mods such as "Move It" and "Fine Road Tool" are good examples to refer to for this sort of stuff.

**Comment by VictorPhilipp** [comment]
Related to #103

**Comment by VictorPhilipp** [comment]
moved
