### ISSUE TITLE
Some suggestions for wiki

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#155]
**Train features:**

1. A dedicated overview page for train-specific TM:PE features would be useful to aid discoverability of those features (eg. without reading all the pages, I would likely have no idea that I could use vehicle restrictions or traffic lights on train tracks).
2. In the road features pages, particularly timed traffic lights, I was already struggling and then the seemingly random introduction of train features made matters worse. Hence I think train features should get their own articles, even if there's some degree of duplication.

**Mod Options:**

EDIT: Just realised there is dedicated page for mod options.

Dedicated page for mod options, even if that links out to other existing pages.

I was trying to find out what a few of the options were about (can't remember which one) and had to wade through a few pages to find it.

----

With your permission I could go in to wiki and make changes?

**Comment by VictorPhilipp** [comment]
Regarding the timed traffic lights article: Adaptive step switching is not limited to train tracks. I used railway switching as an example use case for the feature.

Have you already registered a user in the wiki?

**Comment by aubergine10** [comment]
Not registered yet but will do so tomorrow.

**Comment by aubergine10** [comment]
Acct created: aubergine18

**Comment by aubergine10** [comment]
Just tried editing a wiki page and got following error:

![region capture 13](https://user-images.githubusercontent.com/1386719/41194066-c6701dde-6c0d-11e8-8e69-586751eece01.png)

Whilst editing page: [Options](https://www.viathinksoft.de/tmpe/wiki/index.php?title=Options)

To add following content at bottom of page:

```
===Show Pathfinding Stats===

If you enable this option, a new label is added to the game menu (the one shown when you press Esc in-game, or click the gear button in top-right corner of screen) that indicates the number of Path Finders ("PFs") currently queued.

If the number is very large, something that can happen on large systems or slow computers, it's possible that some vehicles may appear "stuck" while they wait for their path.
```

**Comment by aubergine10** [comment]
closing as non-essenital
