### ISSUE TITLE
Disable pedestrian traffic light for disabled pedestrian crossing

### ISSUE THREAD

**Issue by carsonip** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#156]
First, thanks for maintaining this wonderful mod. The game is so much more fun with it.

Feature request:
Is it possible to disable the pedestrian traffic light for crossings that have pedestrian crossing disabled? Currently vehicles are waiting for pedestrian light to go red before they can move, but there will be no peds crossing because it is disabled.

**Comment by VictorPhilipp** [comment]
Could you clarify your request? Vehicles never wait for pedestrian lights to become red, they rather wait for pedestrians crossing the road.

**Comment by carsonip** [comment]
Makes sense, let me take a closer look. I'll get back to you later.

**Comment by carsonip** [comment]
Yup, the problem is actually the need of a right turn light, because no peds are crossing. It makes no sense to wait for right turn.

**Comment by VictorPhilipp** [comment]
Nevertheless, the pedestrian traffic light overlay could be hidden if the crosswalk is disabled.

**Comment by aubergine10** [comment]
Would it be possible to hide the striped crossing decal (or whatever it is) if the crossing is disabled? That would be fantastic for visual feedback on the map as to which crossings are enabled/disabled.

**Comment by VictorPhilipp** [comment]
I think crosswalks cannot be removed for individual road segments.

**Comment by VictorPhilipp** [comment]
moved
