### ISSUE TITLE
Fails to load or start a new game

### ISSUE THREAD

**Issue by mbtail** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#157]
After loading a game ( and same occurs when starting a new one ) i get an error message.
It says that the mod failed to load and then i get an error message: 
Method not found: 'CitizenAI.SetTarget'. [System.MissingMethodException]

Details:
No details

No other mods are activated at the time. 
The cities skylines version is 1.9.0-f5.

**Comment by aubergine10** [comment]
Could you provide your log files – "output_log.txt" (Windows), "Player.log" (Linux, Mac) and "TMPE.log" files which can be found at the [user path](https://skylines.paradoxwikis.com/User_path)... Upload them to pastebin.com or share them via dropbox/googledrive or whatever and post link here. It will help track down the problem if we can get full error message from the logs.

Also if you're able to share your savegame via Steam and provide a link that would help with recreating the problem. Save games can be shared from Main Menu > Content Manager > Save Games.

**Comment by VictorPhilipp** [comment]
Please update the game to the latest version, 1.10.0-f3.
