### ISSUE TITLE
Bus / others load passengers on unbunching

### ISSUE THREAD

**Issue by carsonip** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#158]
Feature request:
Is it possible to make bus load passengers when they are waiting for unbunching at the bus stop?
Does unbunching also applies to other vehicles (e.g. tram, etc)? If so, it would be great to have this feature for them too.
Thanks.

**Comment by VictorPhilipp** [comment]
@BloodyPenguin This sounds more like a feature request for mods like Improved Public Transport 2.

**Comment by carsonip** [comment]
Right. Just realized IPT2 became compatible with TM:PE a few days ago.
