### ISSUE TITLE
Idee: Andere Textur für Kreuzungen ohne Zebrastreifen. Zusammenarbeit mit NetworkSkins?

### ISSUE THREAD

**Issue by boformer** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#16]
Hey! Das Feature, Fußgängerwege an Kreuzungen zu kontrollieren, ist dir sehr gut gelungen.

Noch cooler wäre es, wenn sich die Texturen auch ändern würden, also in etwa so:

![Kreuzung](http://i.imgur.com/oyXEnCu.jpg)

Dazu wären einige zusätzliche Texturen nötig, und man muss den Rendering-Code verändern. Was hältst du davon?

Ich plane, so ein Feature auch irgendwann in der Zukunft in NetworkSkins einzubauen, inklusive verschiedener Stile (Zebrastreifen, normaler Übergang, Mittelinsel). Es wäre natürlich perfekt, wenn das direkt mit deinem Mod verlinkt wäre, sodass es nicht rein visuell ist.

**Comment by VictorPhilipp** [comment]
Ach hier hast du mich kontaktiert. :-D

Ja, so ein Feature wäre prinzipiell nicht verkehrt. Ich selbst habe mit Texturen noch nicht gearbeitet. Ich kann mir vorstellen, dass es einiges an Arbeit kosten wird, Texturen für solche Kreuzungen zu erstellen.

Wenn du abfragen willst, ob Fußgänger an einem Segment/Knoten die Straße überqueren können, kannst du die Methode `JunctionRestrictionsManager.Instance().IsPedestrianCrossingAllowed(ushort segmentId, bool startNode)` nutzen. `segmentId` ist die Id des Segments und `startNode` gibt an, ob du den Fußgängerüberweg am Startknoten (true) oder am Endknoten (false) meinst.

**Comment by VictorPhilipp** [comment]
moved
