### ISSUE TITLE
Optimize data size

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#160]
Custom data saving/loading should be optimized regarding memory consumption because custom mod data must be represented with less than 16711680 bytes (~16 MB, see ColossalFramework.IO.DataSerializer.WriteByteArray) and because the deserialization process might take a long time.

**Comment by VictorPhilipp** [comment]
moved

**Comment by brunoais** [comment]
Maybe it can be compressed using something like lz4 or zstd before saving...
