### ISSUE TITLE
Parking AI: Cims spawn pocket cars

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#162]
Cims spawn pocket cars after leaving a transport hub.

**Comment by VictorPhilipp** [comment]
This only seems to occur if Parking AI has just been enabled. Pocket car spawning then still occurs for old paths but that becomes alleviated over time.

**Comment by VictorPhilipp** [comment]
Could reproduce the issue with citizens/tourists that originate from outside connections.

**Comment by aubergine10** [comment]
I think I've seen this happen long after Parking AI enabled (eg. > 1 game year, by which time only new paths).

I'll check next time I'm in game to see if it still happens - was mostly around stations as mentioned in OP but there were other locations (eg. bus stops) too.

**Comment by VictorPhilipp** [comment]
Fixed
