### ISSUE TITLE
National roads and train crossings do not show railway crossing with barrier.

### ISSUE THREAD

**Issue by Sipke82** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#163]
National roads and train crossings do not show railway crossing with barrier. Only with one exception when you build a national road towards the rail.

All other national roads show no railway crossing with barriers at all.

**Comment by aubergine10** [comment]
Could this be same cause as #149 - the road asset missing level crossing assets?

**Comment by aubergine10** [comment]
It would be worth reporting to NeXT 2 team - if you can work out which github is the currently active one.

They are missing junction/crossing assets on their national roads - perhaps intentionally?

**Comment by VictorPhilipp** [comment]
This is the same issue as #149. It's not a bug in TMPE but probably a missing asset in NeXT2
