### ISSUE TITLE
Taxis - buffs depending on PT usage?

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#166]
This was going to be a comment in #106 but thought I'd split in to separate issue.

I expect to see high taxi use in following situations:

2. From home to first leg of PT
1. When using train, plane, blimp, ferry

Taxi transfer costs should be muted in those two scenarios.

However, if I use bus, tram, monorail or subway, the opposite is true - I'm far less likely to use taxi after those modes of transport.

Summary:

* Start of journey: Deflate taxi transfer cost (unless cim is poor?)
* Just used plane, train, blimp, ferry? No taxi transfer cost
* Just used bus, tram, subway, monorail? Inflate taxi transfer cost

**Comment by Sipke82** [comment]
Well i'm thinking that taxi use is more based on wealth?

If so, then we can already play around with the probability of taxi usage using the life cycle rebalance mod (https://steamcommunity.com/sharedfiles/filedetails/?id=654707599) where you can edit the xml to tune the likeliness of taxis being used over other form of transport based on the cims wealth. unfortunately it does not provide control for tourists.

And besides that, perhaps this is out of scope for TMPE, and more in scope for mods like IPT2 and TLM?

**Comment by aubergine10** [comment]
How does the pathfinder currently determine which types of transport to use?

You might also be interested in #151

**Comment by aubergine10** [comment]
I'll give the linked mod a try :)
