### ISSUE TITLE
Strange junction crossing behaviour

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#168]
Link to save game for testing: https://steamcommunity.com/sharedfiles/filedetails/?id=1403022578

Points of interest (in the **Industrial Docks** district at ferry pier):

![region capture 15](https://user-images.githubusercontent.com/1386719/40945681-de99433c-6851-11e8-9e3f-9ba99b4054f1.png)

* A = Place where I expect cims going home to exit bus
* B = Pedestrian crossing at junction I expect them to cross
* C = Ped bridge that leads to train station
* D = Stop they end up using (see notes below for context)

When I first set up this transport infrastructure, they were getting off the bus at A, crossing at B and then using bridge C.

However, they were crossing on the "right hand side" (from orientation of the image above) of the junction which was ugly:

![region capture 16](https://user-images.githubusercontent.com/1386719/40945861-6213f482-6852-11e8-8319-3dedfc67ebe5.png)

As you can see from image above, they were crossing to the right of the marked crossing (ie. the "wrong side" of the junction.

No problemo, I thought, I'll just turn off the junction crossing on that side:

![region capture 13](https://user-images.githubusercontent.com/1386719/40945891-85ecdb8a-6852-11e8-9246-36924ea5562c.png)

However, the effect of this was that they ceased getting off the bus at point A and instead stayed on the bus until point D (a much longer journey). After getting off bus at D, they would then walk to the bridge at C.

Occasionally they would cross at point B, but only if they were approaching it from the left-side (from orientation of images above) of that node junction.

It's as if, when approaching from the right-side of that node junction, the remaining ped crossing did not exist. The path finder appears to look for the nearest ped crossing and, if it's disabled, assume there is no way to cross the road at that junction even if the crossing on the other side is still active.

What I expect to happen: Check all suitable ped crossings at junction, not just the nearest one.

**Comment by VictorPhilipp** [comment]
Wow, interesting finding and very well documented! I am not sure if that can be changed without causing a complete mess within path-finding but I will see what can be done.

**Comment by aubergine10** [comment]
I've run in to this issue a few more times.

It seems to also happen on "corner" junctions and "level crossing" (at lest the simple variety with only two road segments involved) junctions too, although additional testing is likely needed to confirm that being the case.

As far as I can tell, the issue does not appear to affect "3+ segment" junctions but again more testing required.

I was just about to do the aforementioned testing when my **Noise Reduction Shurbbery™** ignited and, burning like a fuse wire, engulfed the entire district in flames. It's certainly much quieter now that everything is just rubble. But I digress...

Interim Suggestion:

For affected junction types (inline, corner, level crossing) just have a single "restrict crossing" icon which acts upon the crossings on both sides - it will be cleaner UI and I think more reliable operation from end-user perspective.

**Comment by VictorPhilipp** [comment]
> As far as I can tell, the issue does not appear to affect "3+ segment" junctions but again more testing required.

![grafik](https://user-images.githubusercontent.com/4333935/42724327-5b8b2918-8770-11e8-9905-01ea0df4f8d3.png)

Toggling "A" should prohibit cims from crossing the street at "C" but it also prevents them from moving along "B".

**Comment by VictorPhilipp** [comment]
Fixed
