### ISSUE TITLE
Hide lane arrow

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#169]
I've realised I can hide lane arrows, but only if there's no custom lane connections at the node. Also, if I'm not mistaken, hiding the arrow also means no connections from that lane at the junction/node?

For detailing and general beautification of roads (particularly at transitions between ground, elevated, bridge, etc.) it would be really useful if I could simply "hide" individual lane arrows without affecting connections. And (nice to have) a keyboard modifier (Alt+Click?) on the "hide" button to toggle visibility of all lane arrows for selected segment(s).

There could perhaps be an extra button to toggle visibility of the lane arrow, which would work even if there are custom lane connections for that lane?

Possible icon for button: [eye](https://thenounproject.com/term/eye/190164/)

**Comment by Sipke82** [comment]
There are mods that purpose:
https://steamcommunity.com/workshop/browse/?appid=255710&searchtext=remove+arrow&childpublishedfileid=0&browsesort=textsearch&section=home

**Comment by aubergine10** [comment]
Yes, I am aware of these mods. So far, the only mod I've seen that allows me to remove individual lane arrows is TM:PE. In addition, even with things such as ploppable asphalt, I am often not able to remove the existing arrows without creating floating patches of tarmac.

For example, if I want to close a single lane of a motorway between two junctions (exit and entry), I only want the single arrow removing. I don't want to remove all arrows across all roads and then spend ages manually recreating them just to remove the arrows from that single lane of motorway between the two junctions.

**Comment by VictorPhilipp** [comment]
I believe it's impossible to prevent individual lane arrows from being rendered at specific road segments.

**Comment by aubergine10** [comment]
On the lane arrow changer tool in TM:PE, you get three buttons for each arrow. If I "unselect" each button no arrow is shown. I was just wondering if it was possible to have a "hide" button that has the same effect, but while leaving the lane connections in place?

**Comment by VictorPhilipp** [comment]
Ok, that's possible of course. +1 I would have to create a new data structure that holds the lane arrows and decouple routing decisions from the base game's arrows

**Comment by VictorPhilipp** [comment]
moved
