### ISSUE TITLE
Some nodes act as junctions while they shouldn't (was: Cims dangerously U-turning on national highway)

### ISSUE THREAD

**Issue by Sipke82** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#170]
I've enabled u-turn on junction. Nevertheless i think they should never perform a u-turn on the middle of a national highway.
![image](https://user-images.githubusercontent.com/30873812/40989942-9f6ec8dc-68ef-11e8-9262-2001fc4d79d6.png)

**Comment by VictorPhilipp** [comment]
definitely drunk! Does that happen regularly? TMPE only allows u-turns at junctions and transitions (where two different road types meet)

**Comment by Sipke82** [comment]
It happens all the time! Weirdly i havn't spot other locations yet. And i use quite some national roads. maybe it has something todo with the nearby (highway based) roundabout?

**Comment by Sipke82** [comment]
I removed the entire road  and railway, and rebuilt it now this stretch is ok. However somewhere down the medium road the issue is appearing now.
![image](https://user-images.githubusercontent.com/30873812/41064257-53f92eaa-69db-11e8-95f4-f05bd4bed0a3.png)
I've selected everything with the move-it mod so you can see the segments and nodes. The middle node is somehow behaving as a junction. cars from both directions are taking u-turns + pedestrians are crossing here towards and from the train station

**Comment by VictorPhilipp** [comment]
Internally they are not considered as junctions but as "bent" nodes. Nodes are considered as bent by the game if the angle between the two connected road segments is not accurately straight (0°). I always assumed that labelling nodes as bent required some minimum angle between segments but I was wrong obviously. TMPE offers junction restrictions for junctions and bent nodes.

I could add two more options that control whether crossing / u-turns are allowed at bent nodes. But I don't know if any player will ever understand what those options do. xD

**Comment by Sipke82** [comment]
I tried to come up with a reason to allow cars U-turn and pedestrians crossing at "bent" nodes, but couldn't come up with one. 
To create pedestrian crossing you could just use the following mod:
https://steamcommunity.com/sharedfiles/filedetails/?l=dutch&id=427258853
And U-turns on the middle of the roads, seems like madness to me? (especially in corners ;-) )

So shouldn't it just be disallowed in any case? (instead of adding options) And just act the same as "straight nodes"?

**Comment by aubergine10** [comment]
When using Move It mod to edit roads, you can enable "Snap" mode and it will snap segment curvature to achieve 0° angle at the nodes: [tutorial vid](https://www.youtube.com/watch?v=pte_uz-3khg)

I agree with **Spike82** that u-turns at bent nodes should be disabled by default (ie. no need for options in mod settings ui). Although standard behaviour could be defined by settings in xml config file?

As an end-user, my preference would be:

* No u-turns at bent nodes, ever, even if "Allow u-turns" mod option enabled
    * Reckless drivers could still choose to do u-turns at bent nodes
* Using junction restrictions tool on bent nodes:
    * Can toggle crossings
    * Can toggle "change lanes"
    * The UI for u-turns would not be shown (unless XML config says otherwise?)

**Comment by aubergine10** [comment]
Addendum: If "Enable highway specific rules" mod option selected, u-turns should be disabled (by default) on all junctions/nodes where a highway segment exists. User could still use lane restrictions tool to customise individual nodes.

**Comment by Sipke82** [comment]
I think that crossings at "bent" junctions should be defaulted to False as well. 

So, taken together perhaps this issue can easily be resolved by changing the default states of the junction restrictions of bent nodes to not allow U-turns and do not allow crossings.
