### ISSUE TITLE
The curious case of Anna Finch

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#171]
This is Anna Finch...

![region capture 20](https://user-images.githubusercontent.com/1386719/40991444-b62341c4-68eb-11e8-8992-685ce94b8d7b.png)

She works at the BTB College in Lower Garnet, and next door is the BTB Rehab Center where she parked her car:

![region capture 21](https://user-images.githubusercontent.com/1386719/40991494-dc5bf9e4-68eb-11e8-8a88-92516d6788cc.png)

You'll notice she's not taking her car home with her.

I was investigating a strange transport case at the rehab center (will report in separate issue) when I noticed Anna walking round the side of the rehab center to her car... and when she got to the car she changed her mind and started walking home.

Maybe finding parking space was so much hassle that she decided to just leave her car there overnight rather than repeat the ordeal the following day? (Lower garnet is practically devoid of parking spaces, she was super-lucky to get one so close to work).

And where is her home?

![region capture 25](https://user-images.githubusercontent.com/1386719/40991565-11621c04-68ec-11e8-8802-a78521a574ef.png)

It's next to the university in Garnet, just a short drive away. And there's 100+ empty spaces in those parking garages on the other side of the university.

Link to save game: [in workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1403538203)

Link to player.log: [on google drive](https://drive.google.com/file/d/1NU9QE_3aCHX-_OiGirWJa-EcjFTIw3gX/view?usp=sharing)

**Comment by VictorPhilipp** [comment]
This can happen if:
* Anna could not find a car path to her home (problem/bug)
* Anna really changed her mind in that very moment (can happen, depending on the current traffic situation)
* the vehicle limit is reached (16384)
* the parked vehicle mysteriously disappears (does not seem to apply here)

**Comment by aubergine10** [comment]
The route to her home seems valid; 120 families in that building IIRC (b/c RICO) and I've watched lots of other cims travel between it and the College next to the Rehab Center. Due to fairly high use of PT I suspect the vehicle limit wasn't reached but can't be sure without some way to count (ISTR there was a mod that shows limits so I'll install that so I can do further investigation).

**Comment by VictorPhilipp** [comment]
@DaEgi01 Yes, correct. But if path-finding fails TMPE tries to find a walking route instead.

**Comment by aubergine10** [comment]
I found the mod that lists limits: [Show More Limits](https://steamcommunity.com/sharedfiles/filedetails/?id=531738447&searchtext=limits) - assuming it is compatible with recent versions of the game, I will do some investigations tomorrow to see if I can rule out the vehicle limit cause.

I also checked for things like fires (you mentioned elsewhere that they cause nearby segments to be marked as blocked) but could find none in the relevant districts.

Is there some way to enable a debug mode for TM:PE that adds additional logging should path finding fail (eg. if she was unable to drive home, the log file would get some details of what went wrong)?

**Comment by aubergine10** [comment]
Problem not caused by limits:

![region capture 14](https://user-images.githubusercontent.com/1386719/41097672-b7f7be38-6a50-11e8-93db-0b7a9c3d26e6.png)

I did some more investigation in to the residential building. It's RICO and I'd move it (with Move It mod, snapping enabled). Looks like I somehow rotated the building by 90 degrees (it's "official" entrance does not point directly at the road).

However, cars are still parking there and peds/cyclists are still entering/exiting from the road. As far as I can tell, the "official" entrance for the building is within 2 zoning tiles of the road.

**Comment by aubergine10** [comment]
Saw this issue again last night, only this time with a tourist. He was parked up near observatory and was "going home" - he walked up to his car, then suddenly decided to leave the map via public transport...

This seems even more weird than the Anna Finch case described above. There were no blocked routes from observatory to highway, traffic was flowing normally in all areas, no fires etc., limits similar to screenshot above.

BTW: In relation to the building where Anna Finch lives, I've tracked some other cims going home to that building and they did use their cars.

Maybe some of my cims are losing their car keys and only realising upon reaching the vehicle?

**Comment by aubergine10** [comment]
Since recent updates, this seems not to happen any more (or at least much less) so closing this ticket for now.
