### ISSUE TITLE
Emma Blackwell doesn't stop for level crossings

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#172]
Emma was driving home from work (she works at the Emergency Shelter in Garnet).

Her home is on the edge of the map in the Lakeside Services district, several miles down the M6:

![region capture 24](https://user-images.githubusercontent.com/1386719/40995330-b532f1e6-68f6-11e8-91c6-f7f7fa28c9f8.png)

There are several car parts in that district, and there's usually free space in the multistorey car park adjacent to the amusement park.

Background:

When I first entered FP cam on her vehicle, it was joining the M42 via a new junction connecting to Garnet - a somewhat strange route as there's a closer connection to the M6 (which goes down to Lakeside) from the Emergency Shelter where she works. There are two large multistorey car parks next to the Emergency Shelter (you can see them in a last pic in #171) - I assume she was parked in one of those whilst at work. It seems she took scenic route.

Anyway, she drove to the trumpet junction connecting M42 to M6, and then proceeded to drive in to Lower Garnet via the junction from M6. She drove past the BTB Rehab Center, which is situated between the BTB College and a large Crematorium (complete cradle-to-grave services eh?) and then, after turning round at the end of that road, she toured the residential area in Lower Garnet (presumably searching for parking).

The vehicle then drove to the cul-de-sac next to the Emergency Shelter in Garnet; there is access to one of the large multistorey car parks from that road - why not park there (100+ spaces available at the time) and take train to Lakeside? The vehicle turned round and promptly drove straight through closed level crossing barriers and did another tour of Lower Garnet.

At that point I exited FP cam to investigate what was happening (assumedly a struggle to find parking). The vehicle once again ended  up driving to the cul-de-sac next to the Shelter in Garnet, turned round and drove, once again as luck would have it, straight through the closed level crossing barrier.

From there she drove to the Rehab Clinic, parked up and, as far as I can tell (got distracted by strange behaviour of Anna Finch #171 at that point) she found her way to the train station and went home.

For reference, here is location of Rehab Center for comparison to earlier image showing where her home is (note the "Lower Garnet" text in both images):

![region capture 22](https://user-images.githubusercontent.com/1386719/40996419-9dc3eeea-68f9-11e8-9ec7-21ad9d8e217d.png)

Save game and player.log: See links in #171

**Comment by VictorPhilipp** [comment]
Duplicate of #129 regarding ignoring level crossings

**Comment by aubergine10** [comment]
I have the traffic lights feature enabled, so not sure if this is same bug?

**Comment by aubergine10** [comment]
Unable to reproduce this for a few days now, so going to close this issue. Will re-open if it happens again (in a repeatable manner).
