### ISSUE TITLE
Is "dummy traffic" supposed to leave the same way it entered?

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#175]
I've noticed lots of outside traffic enters the map, finds a place to turn round, and then leaves by the same outside connection that it entered from.

A good place to spot this is near the Industrial Docks district in the save linked below. Where the road connects to the highway (marvellous road design on my part), I had to create a small cul-de-sac road to soak up all the "u-turners" that entered from M42 outside connection with the intent of leaving the way they came in. They were clogging up the road at the nearby passenger train station which is how I became aware of them.

I imagine it's "a feature" of vanilla game to ensure that dummy traffic exists even if there's only a single outside connection. However, as an end-user, it seems odd - maybe if there's more than one outside connection an additional check could be made to ensure they don't leave by the same node that they entered on? If not, no worries as there is trivial workaround. I guess the issue is exacerbated by the fact that I've not yet set up proper motorway junctions in that area.

Link to save game: [in workshop](https://steamcommunity.com/sharedfiles/filedetails/?id=1403538203)

Link to player.log: [on google drive](https://drive.google.com/file/d/1NU9QE_3aCHX-_OiGirWJa-EcjFTIw3gX/view?usp=sharing)

**Comment by VictorPhilipp** [comment]
Yes, both source and target outside connections are selected randomly by the game. That also means that if there is only one outside connection cars may leave the city at the same connection where they originally departured.
