### ISSUE TITLE
"Disable spawning of pocket cars" feature kills rush hours

### ISSUE THREAD

**Issue by DaEgi01** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#18]
Hallo :)
seems that the "Disable spawning of pocket cars" feature works too well,
it also seems to kill the spawning of the "Rush hour" mod which is pretty bad.
I love too see and handle crazy amounts of traffic on my roads, which is what Rush hour together with your mod is so great for.
That is what this game for me is about.

Tested with a small town (6k) and the Show More Limits mod.

During regular hours the citizen instances count is around 3,5k.
During rush hours with "Disable spawning of pocket cars" off, it is around 6k.
During rush hours with "Disable spawning of pocket cars" on, it is around 4,5k.

Huge difference in traffic volume!!!!

Yet I love the "Disable spawning of pocket cars" feature.
All the spawning of cars at a train station or harbor is so stupid.
So don't just remove it... there must be a way to make it compatible!!!

**Comment by VictorPhilipp** [comment]
Suggested solution (already in the process of being implemented):

**1. If a cim owns a parked vehicle:**
1.1 If their current path requires using a car then they first go to the parked vehicle and enter it.
1.2 If there is no free parking space near the target location: Use **Advanced Parking AI** (https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/29) to find an alternative parking space.
1.3 If the process of finding a parking space fails _N_ times: cim and car despawns.
**2. If a cim does not own a parked vehicle:**
2.1 Try to spawn a parked vehicle in the vicinity of the starting point.
2.2 If successful, go to 1. Else abort.

**Comment by DaEgi01** [comment]
Hmmm... I don't like 1.3 and 2.1 since it is not realistic, but I guess it is a necessary evil.
Thank for doing such awesome stuff for C:S!!!

If I could wish me a solution, I guess I would go for the following:
1.3 If the process succeeds park the car. If the process of finding a parking space fails N times: keep looking and increase the searching radius, but increase unhappiness for each time it fails.
After N+M times park illegally wherever possible (I guess the game engine does not work like that though ;))
There should be a way to query parking situation data for each cim individually and a district aggregated to be able to find out how bad it is.
Remember how often parking failed for each cim. If the last x times parking took more then y tries, the cim should avoid using the car at all. 

2.1 try to call a taxi if taxis are available.
if there is no taxi available or if it too much time has passed, pick another route to destination and walk if necessary but reduce happiness.

Anyway ... any improvement is great, so thanks again :)

**Comment by VictorPhilipp** [comment]
First working version is implemented 1.8.0.

"Illegal parking" (let's say parking on a sidewalk) is not doable (at least currently) because this would also require a mechanism to remove those parked cars (e.g. a towing service). Additionally, cims would need to evade illegally parked cars on a sidewalk.

I like the idea of calling a taxi or using public transport in general. However, there are cases where public transport is unavailable AND the target location is not accessible by walking.
