### ISSUE TITLE
1.10.8 broke ParkingAI :-(

### ISSUE THREAD

**Issue by Sipke82** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#183]
Cars are stopping in the middle of the highway and other roads, "Thinking of a parking spot"
The Pathfinding stats never seems to go near zero... which did happen with previous version. as a result CPU gets overloaded, making the game unable to play anymore. For now I've disabled Parking AI.

Could you roll back to previous version for now?

**Comment by Sipke82** [comment]
Thanks for the update! Just to inform you, the ParkingAI is still bugged, it's a real strain on the CPU now, while in 1.10.7 it wasn't! could you please revert to that while a better solution might be in the pipeline....

**Comment by VictorPhilipp** [comment]
I am looking into this issue now.

**Comment by VictorPhilipp** [comment]
Fixed
