### ISSUE TITLE
1.10.1-f2 (July) game patch breaks PT when TM:PE active?

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#186]
Been seeing lots of reports over past 24 hours that PT is broken (cims no longer use PT) and discussions seem to be swaying towards TM:PE being culprit (I've not tested yet but will do so this evening).

Apparently there's been a game update to fix some Park Life bugs, and it's somehow changed the way PT works or something:

* [Patch notes and discussion on reddit](https://www.reddit.com/r/CitiesSkylines/comments/8w1se2/cities_skylines_1101f2_patch_notes/)
* [Reports from MOM users on Steam](https://steamcommunity.com/sharedfiles/filedetails/?id=816260433&searchtext=metro+overhaul)
    * But, note this from Lazarus:
    * > I have been working on looking at why cims are not using public transit. Looks like it is due to an update in the game code as it seems to still happen even with the older version of this mod (from January).
    * He mentioned this in response to a separate issue:
    * > Ok so if you have old saves, please please load them up without subscribing to MOM and ensure that the connections outside the 25 square zone still work. Then try with TM:PE (if you have it).
    * Users then started disabling TM:PE and reporting that PT was working again
* [Reports from TM:PE users on Steam](https://steamcommunity.com/sharedfiles/filedetails/?id=583429740&searchtext=president)

Possible culprit:

> Fixed: Public Transport Line lengths have inconsistent divergences between different
transport types

**Comment by aubergine10** [comment]
Another [report on reddit](https://www.reddit.com/r/CitiesSkylines/comments/8wkb5b/zero_metro_usage_in_city_bug/)

**Comment by aubergine10** [comment]
Temporary workaround: Disable TM:PE and restart C:SL (ie. exit to desktop first before playing a save). If that doesn't work, completely unsub TM:PE (some users reported needing to do this in order to get their PT working again).

**Comment by aubergine10** [comment]
And another [report on reddit](https://www.reddit.com/r/CitiesSkylines/comments/8wgykj/07052018_update_reduced_weekly_transit_ridership/)

**Comment by aubergine10** [comment]
People are reporting that reverting to v1.10.7 or v1.10.3 has solve the issue for them. Hopefully that narrows it down to a smaller number of commits to investigate?

Via [reddit discussion](https://www.reddit.com/r/CitiesSkylines/comments/8x2z52/tutorial_fix_traffic_manager_president_edition_in/).

**Comment by gaetanLyon** [comment]
Hi,
In fact all the previous versions don't work. when you unsubscribe and subscribe the mod, utilisation of publics transports start to grow and after, decrease again to 0 (that  can be confusing us, and that why somes people says "it's works"). So the problem is not the update of this mod but really the changes caused by the patch. 
Regards

**Comment by aubergine10** [comment]
Some MOM users are reporting that even when not using TM:PE, their are seeing their PT usage drop over time.

**Comment by rusky234** [comment]
Try disabling the PT transtition cost thing in the TMPE menu. And alsp change the PT transition cost in the universal config file

**Comment by Xyrhenix** [comment]
I went over the changelog of the latest Skylines patch and noted that they updated the version of Unity to 5.6.6f2. I have some doubts as to whether it is related but it feels important to mention regardless.

I would usually play the game with preventing unnecessary tranfers enabled, to make citizens take a more direct route. When I noticed PT usage dropping I did enable it to try boost PT usage figures, but that had no impact on things. I haven't yet changed the transition cost in the universal config file, so I will try that and see if it yeilds any results.

**Comment by rusky234** [comment]
I have set my min and max values just slightly above 0 and aslo unchecked the transition cost thing. My existing PT lines carry about 3k ppl and it is not noticably different than pre parklife numbers. I also created a new metro line in latest TMPE version and ppl seem to reasonably use it.

**Comment by Videonauth** [comment]
@rusky234 Can you please provide the exact values you using?

**Comment by aubergine10** [comment]
The PR linked above fixes PT for me (and everyone else who's tried it).
