### ISSUE TITLE
Passengers get off bus and walk vehicle lane

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#193]
I've noticed. since the new pathfinder was introduced in recent mod update, that passengers are doing strange things after getting off the bus...

Context:

* 4 lane road, 2 way, outer lanes are bus lanes
* Bus stop is in the bus lane
* Parking AI is off (not currently tested with it on so this might be irrelevant)
* The city is left-hand traffic (I've not tested with right-hand traffic)

Some passengers get out and start walking down the road - in the vehicle lane next to the bus lane. When they reach a node (of any type, I assume, but not yet tested), they spawn pocket cars.

This looks really odd. It's similar to the weirdness that happens near outside connections when cims are moving in to the city - walking in the road then suddenly spawning cars.

While there has always been some post-bus pocket car spawning (even in vanilla game), it's always taken place on the pavement. This recent behaviour of them walking down the road has just make it much more obvious.

What I would expect to happen:

* A cim using PT should not pocket car
* If part of the journey would cause pocket car, it would be better to do whole trip by car (or taxi?)
* Only time pocket car should occur is if part of the journey is only possible via PT and the remainder is only possible by car (eg. too far to walk after getting off bus) - even then, taxi or bicycle should be used instead if possible.
* If a cim does pocket car, it should be from the pavement, where it's visually less obvious

**Comment by VictorPhilipp** [comment]
At one occasion I have also seen a car driving on a monorail track. Might be a related problem.

https://youtu.be/V7BE9NiF-Y8

**Comment by VictorPhilipp** [comment]
I also have seen that happening in the past, but only on the NExt2 3-lane and 4-lane roads (1+2, 1+3, 2+2).  Does the problem also occur for on the vanilla 4-lane road (with median) or only on NExt(2) roads?

**Comment by Videonauth** [comment]
As far i have seen the Pocket Cars happen on the worst places, no matter if NExt2 Roads or Vanilla, running advanced parking AI luckily prevents those. Maybe a segment/Lane restriction for spawning Cars at all would be a solution, as I found out when replacing the street with the same street in many cases solves the problem, as well as rerouting some of the public transit to have a stop on the exact place where the spawning happens. Bu as I said as soon you use parking AI which actually with 1.10.10 works wonderfully without hitting the CPU load stops this behavior completely.

**Comment by aubergine10** [comment]
This is the road where I noticed people walking down the vehicle lane: https://steamcommunity.com/sharedfiles/filedetails/?id=1307053634&searchtext=uk+roads+bus

I only have 2 segments of vanilla road in my city currently (a 6-lane bridge over a motorway).

**Comment by Videonauth** [comment]
Here another Screenshot of this happen, with another issue on top of it. Some of those lane walkers stand then on the lane and stating they are taking public transit to go home. Guess they are waiting for taxi. They simply stand there and slow down traffic. 
![screenshot 29](https://user-images.githubusercontent.com/9640109/43040485-4b91804a-8d45-11e8-89c9-c986ade54b4f.png)

**Comment by aubergine10** [comment]
Created separate issue for cims that wait in road for taxis: #208

**Comment by VictorPhilipp** [comment]
moved
