### ISSUE TITLE
City not loading with pathfinding error (Field '.PathUnit.m_speed' not found.)

### ISSUE THREAD

**Issue by Laurensvandendriessche** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#202]
After updating to the latest version, my city no longer loads with the following error in the output log:

Path find error: Field '.PathUnit.m_speed' not found.
  at TrafficManager.Custom.PathFinding.CustomPathFind2.PathFindThread () [0x00000] in <filename unknown>:0   [Core]

After reverting to .3-.5 the city loads again, so my guess it has something to do with the new pathfinding that was implemented in the latest revisions.

**Comment by aubergine10** [comment]
Are you running the latest version of Cities Skylines? That property was added in the Park Life update (both free and paid DLC updates).

**Comment by Xyrhenix** [comment]
A few people have reported this issue on the mod's page on Steam. The one person who provided an output logfile was using Skylines 1.10.0-f2, and an update to this mod patched the PT disuse bug in mid July.

**Comment by VictorPhilipp** [comment]
Update your game to the latest version.
