### ISSUE TITLE
Service vehicles doing u-turns where they shouldn't

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#203]
In mod settings, I've disabled the option that would allow vehicles to u-turn by default.

However, I've noticed lots of service vehicles doing u-turns most notably if they have to use a long cul-de-sac to turn around to reach a destination. After passing the last proper junction, they'll drive for a segment or two and then u-turn in middle of road. The places where they u-turn, that I've observed so far, are "non-junction" nodes where two segments of same road type meet.

If you need a save or other infos, let me know.

**Comment by Xyrhenix** [comment]
Maybe related to #207 ?

**Comment by VictorPhilipp** [comment]
No, this can't be related to #207 (speaking on a technical level).
@aubergine10 Is this still happening for you after the 1.10.11 update?

**Comment by aubergine10** [comment]
It seems to be fixed, although I noticed last night there were bus routes showing u-turns (I've since seen another update that mentions that bug being fixed so will test that later).

**Comment by aubergine10** [comment]
It all seems fixed, closing this issue.
