### ISSUE TITLE
Parking AI seems unreliable

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#204]
My city is filled with parking spaces, many of which are empty, yet I see vehicles travelling to many destinations roaming around looking for parking.

Context:
* Left side driving
* Lots of cul-de-sacs around areas where cims are trying to get to

If you need a save or any other infos, let me know.

**Comment by aubergine10** [comment]
#184 would greatly alleviate this issue.

**Comment by VictorPhilipp** [comment]
moved
