### ISSUE TITLE
Bus lines are rendering u-turn

### ISSUE THREAD

**Issue by karelkrivanek** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#207]
If a bus line should end by turning around a block it is instead rendered as a u-turn after the last stop. But the bus will continue as it should and don't (edit) do the u-turn. This seems to be happening after the 1.10.11 update.

![screenshot 7](https://user-images.githubusercontent.com/10894433/43033818-63fba490-8cd1-11e8-8437-c909d285d582.jpg)

EDIT: made a type, buses DON'T do u-turn at the of the line. They go round the block.

**Comment by Videonauth** [comment]
Can confirm that this happens, makes placing bus lanes extremely difficult, but not impossible. I worked around by placing a stop there to force them to take the right path.

**Comment by Xyrhenix** [comment]
This has been happening with me too. I've been able to create bus routes fine, but it's kind of difficult getting the buses to go the way they need to go sometimes. Theorised that it could be related to the fixes for "Heavy vehicles are unable to u-turn at dead ends" or "Buses do not prefer lanes with correct lane arrow."

**Comment by VictorPhilipp** [comment]
Fixed and updated!
