### ISSUE TITLE
Crossing restrictions do not work at intersection between road and highway

### ISSUE THREAD

**Issue by SquareBeard** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#212]
As the title says, crossing restrictions do not work at intersection between road and highway. Pedestrians will still cross the road even with the restriction applied.

**Comment by aubergine10** [comment]
Do you have a screenshot showing the road configuration? Also, which road and highway are you using (from the vanilla game, or assets from workshop)?

**Comment by SquareBeard** [comment]
![image](https://user-images.githubusercontent.com/5481247/43278494-916fb5ea-910b-11e8-8d34-82ee7ad33ac3.png)

If you think it's relevant then I will do more tests, because there are too many different roads in that screenshot.

**Comment by VictorPhilipp** [comment]
I think it has nothing to do with the road type but with the fix I implemented for #168. I have to check on which side pedestrians want to cross the road and then determine whether the restriction may apply or not.
