### ISSUE TITLE
Dummy traffic only entering via one outside connection

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#215]
I have a city with 2 outside road connections (south and west sides of the map, with a path between them).

The dummy traffic in my city is only entering via a single outside connection.

Will upload a save illustrating the issue some time in next 24 hours.

Was something modified in relation to #175 ?

**Comment by VictorPhilipp** [comment]
No, I have not changed anything for #175.

**Comment by VictorPhilipp** [comment]
moved
