### ISSUE TITLE
Abulances should not stop trains at crossings.

### ISSUE THREAD

**Issue by Krutonium** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#218]
![20180803184751_1](https://user-images.githubusercontent.com/3945538/43668943-c0ba5b32-974d-11e8-9335-ed5f889fe6fa.jpg)

In a scenario like this, an Ambulance can and does stop a train from continuing - which makes the signals stay closed, and deadlocks the intersection until either the train or the ambulance despawns.

Unrelated, but is there a way to make Ambulance Drivers at least somewhat obey road laws and stops switching sides of the the highway at every node?

**Comment by Krutonium** [comment]
![20180805153210_1](https://user-images.githubusercontent.com/3945538/43689210-d60508ac-98c4-11e8-8ff0-63730f8a30d4.jpg)
![20180805153214_1](https://user-images.githubusercontent.com/3945538/43689212-d6148e30-98c4-11e8-98a3-6ea88829a3a0.jpg)

**Comment by aubergine10** [comment]
I had similar problem, most notably when I put medical center next to a level crossing lol.

I found the  solution was to ensure that vehicles weren't allowed to enter the junction until clear; disable "Allow/disallow vehicles to enter a blocked junction" for the road segments in [Junction Restrictions](https://www.viathinksoft.de/tmpe/wiki/index.php?title=Junction_restrictions) for the level crossing.

IMO the mod should disable road vehicles from entering blocked level crossing by default, regardless of mod settings (i.e. treat level crossings as unique situation). I think currently level crossing is treated sort of like traffic light on normal road junction, which is not suitable approach for a junction where some segments are dedicated right of way tracks.

**Comment by Krutonium** [comment]
Apparently this has since been fixed, though the issue was never closed. [See Here](https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/11#issuecomment-461598332)
