### ISSUE TITLE
Suggestion: use parking lane free spots to let emergency vehicles override

### ISSUE THREAD

**Issue by Gordon-Dry** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#219]
When a non-emergency vehicle gets aware of an emergency vehicle behind (in emergency mode ofc), try to go to a free spot of a parking lane if available nearby, let the emergency vehicle pass by and continue on the road.

**Comment by VictorPhilipp** [comment]
👍

**Comment by VictorPhilipp** [comment]
moved
