### ISSUE TITLE
Traffic ignores lane turns limits in best path calculation and choose a long path instead of choosing the shortest one

### ISSUE THREAD

**Issue by zdo** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#220]
# Abstract

It seems that traffic doesn't count how the calculated path is long and takes only the first path it found. 

May be I'm wrong the "diagnosis", but please take a look at these pictures.

# More information

## First example

So, a lot of trucks goes to right on that intersection. Lets take one of them.

![20180814214936_1](https://user-images.githubusercontent.com/242153/44112265-4deab5f2-a00d-11e8-9dc7-ee18b512e9fb.jpg)

It does turn right here.

![20180814214943_1](https://user-images.githubusercontent.com/242153/44112398-ac515b3c-a00d-11e8-9d22-e1408497b0a6.jpg)

"Lane 3" is limited only to right turn.

![20180814214954_1](https://user-images.githubusercontent.com/242153/44112413-b980ea34-a00d-11e8-84df-9b84e4ecb78d.jpg)

Obviously, if "lane 3" is choosen, the path displayed on screenshot is completely correct. But why the truck has choosen exactly "lane 3"? "Lane 1" or "lane 2" would give much shorter route.

And if I allow going forward for "lane 3" - it goes well.

![20180814214959_1](https://user-images.githubusercontent.com/242153/44112595-2bbe8052-a00e-11e8-8e96-ee7a4d5baa44.jpg)

![20180814215026_1](https://user-images.githubusercontent.com/242153/44112599-2fc13f46-a00e-11e8-8970-c9902e67cb1d.jpg)

## Second example

It doesn't occur only on circles.

Lets take the same situation but with _fixed_ "lane 3": it's allowed now to go forward and right for it.

There is strange truck again:

![20180814214737_1](https://user-images.githubusercontent.com/242153/44112753-a6cc8d16-a00e-11e8-893f-4e8e963f7879.jpg)

Why does it take such weird left direction?

There is the same situation on intersection:

![20180814214752_1](https://user-images.githubusercontent.com/242153/44112794-c569ae02-a00e-11e8-93e1-a7058ba73238.jpg)

Lets move closer:

![20180814214756_1](https://user-images.githubusercontent.com/242153/44112798-c884647e-a00e-11e8-979e-07948c99040e.jpg)

Here's how the lanes are set up:

![20180814214816_1](https://user-images.githubusercontent.com/242153/44112814-d498509a-a00e-11e8-96cd-6b74661a5c24.jpg)

And again - if I enable moving forward for "Lane 1", it goes well.

**Comment by zdo** [comment]
> Vehicles can only change lanes at nodes.

**Yeah, this does the trick, thanks!**

I really have lane connectors here:

![20180814223025_1](https://user-images.githubusercontent.com/242153/44113771-dcfd0c32-a011-11e8-99ab-0169837791fe.jpg)

![20180814223032_1](https://user-images.githubusercontent.com/242153/44113811-f9804770-a011-11e8-90ba-125de17a0ce0.jpg)

I has removed them - and it works perfectly:

![20180814223313_1](https://user-images.githubusercontent.com/242153/44113917-4b779a60-a012-11e8-82cb-46f7c5006760.jpg)

The same issue is on the second intersection I mentioned above:

![20180814223431_1](https://user-images.githubusercontent.com/242153/44113938-5e1d496c-a012-11e8-8cef-348d06975cb9.jpg)

So, the outcome is:

> Vehicles can only change lanes at nodes. Keep that in mind.

Thanks!

**Comment by DaEgi01** [comment]
be careful with lane connectors.
i messed up with them too often :)
they work wonders if done right and wreak havoc if done wrong.
its a good idea to check the traffic routes by clicking on the segments after you have "tuned" your intersections.
