### ISSUE TITLE
Timed light indicator only visible when any timed light node is selected

### ISSUE THREAD

**Issue by Xyrhenix** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#222]
Yay for lengthy title.

Game specs: Skylines 1.10.1-f3 (latest version available).
TM:PE version: 1.10.12 (evidenced by below screenshots).

Other information will be given if requested.

When using TM:PE's timed traffic light tool, I found that timed light are only displayed when a node already connected to **any** set of timed lights is selected. See below screenshots.

Absense of timed light indicators with no nodes selected.
![image](https://user-images.githubusercontent.com/39814064/44356364-0d093100-a4a7-11e8-80d4-e3f2045b5a7b.png)

Absense of timed light indicators with random non-timed node / junction selected.
![image](https://user-images.githubusercontent.com/39814064/44356415-3629c180-a4a7-11e8-806c-2a2289df36a2.png)

Timed lights present when any timed light node selected, even if it's not part of the timed light you've selected.
![image](https://user-images.githubusercontent.com/39814064/44356458-4d68af00-a4a7-11e8-9ffd-66b0d7ab9934.png)

![image](https://user-images.githubusercontent.com/39814064/44356478-607b7f00-a4a7-11e8-912e-bb4b25bcdb20.png)

I believe the above to be a bug.

While on the subjects of lights, are the timed indicators supposed to show up when you are using the manual light feature of the mod? They don't at present, and I was wondering if they are missing from there too. If they're not displayed there, could they be?

The timed light overlay works while the TM:PE menu is open, but not when it is closed. I am guessing this is expected behaviour, but am noting it anyway in case it is not.

**Comment by VictorPhilipp** [comment]
Expected behavior:
If the "Timed traffic lights" overlay is enabled, timed light icons should show up when the TMPE main menu is opened.
If the overlay is disabled, timed light icons should only show up if the timed traffic light function is selected from the main menu.
