### ISSUE TITLE
traffic lights for monorails

### ISSUE THREAD

**Issue by t1a2l** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#224]
For some reason roads with monorail tracks get traffic light and pedestrian lights for the monorail. It behaves like a tram although it is not.

**Comment by VictorPhilipp** [comment]
You mean that toggling monorail lights affect pedestrian lights? That's a bug.

**Comment by t1a2l** [comment]
I mean that monorail should not have traffic lights at all. they don't interfere with traffic at all. Also on roads with monorail tracks you can't change the speed limit of the monorail.

**Comment by VictorPhilipp** [comment]
Ok.

You can change the monorail speed limit by holding `Ctrl`. :)

**Comment by VictorPhilipp** [comment]
Well, Monorails interfer with other monorails. However, I agree that monorail traffic lights are generally not required on monorail road <-> road junctions.
