### ISSUE TITLE
Bus routes: Pathfinding ignores 1-way directions in bus terminals

### ISSUE THREAD

**Issue by aubergine10** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#230]
Example assets that exhibit the problem:

* https://steamcommunity.com/sharedfiles/filedetails/?id=922683980&searchtext=
* https://steamcommunity.com/sharedfiles/filedetails/?id=868718614&searchtext=
* https://steamcommunity.com/sharedfiles/filedetails/?id=534580194&searchtext=

All those assets have 1-way networks inside them, but when creating a bus route it seems to treat the networks as bidirectional. This completely wrecks the concept of bus terminal buildings.

**Comment by VictorPhilipp** [comment]
moved
