### ISSUE TITLE
Not saving changes

### ISSUE THREAD

**Issue by law-kun** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#231]
I can make changes to lane changes, speed limits, etc no problem. But when I load the game again all my changes have mysteriously vanished. Here are the output and tmpe logs, I hope I have the right files. 

lawenzo
[output_log.txt](https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/files/2430511/output_log.txt)
[TMPE.log](https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/files/2430512/TMPE.log)

**Comment by Xyrhenix** [comment]
Need to load a city and try save TMPE stuff and then send those logs. The ones you posted here show you didn't load a city or TMPE isn't enabled).

```[Info] @ 23078 Traffic Manager: President Edition enabled. Version 1.10.12, Build 1.0.6797.38332 for game version 1.10.1-f3
[Info] @ 189440331 Loading global config from file 'TMPE_GlobalConfig.xml'...
[Info] @ 189824517 Global config loaded.
[Info] @ 190220323 Writing global config to file 'TMPE_GlobalConfig.xml'...
[Info] @ 884596139 Traffic Manager: President Edition disabled.
```

**Comment by VictorPhilipp** [comment]
Does not
