### ISSUE TITLE
Correct a long-standing mistake in the Russian translation and interface for some languages

### ISSUE THREAD

**Issue by vitalii2011** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#235]
- Corrections proposed recently here again. Now there is a very incorrect translation of the "98. ... Allow vehicles to enter a blocked junction"
- Interface: https://i.imgur.com/CShumdv.jpg

**Comment by aubergine10** [comment]
@vitalii2011 did this ever get fixed?

* Yes? Please close this issue
* No? Please report issue on new fork of the mod here:  https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues

**Comment by krzychu124** [comment]
Fixed 20 days ago 😉  9d482e518401fb2a77f05837f3000cb5dbe73e0b

**Comment by vitalii2011** [comment]
> 
> 
> @vitalii2011 did this ever get fixed?
> 
>     * Yes? Please close this issue
> 
>     * No? Please report issue on new fork of the mod here:  https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues

I probably missed the message of the author that further development will be engaged in other people. Tell me: where is it?

**Comment by aubergine10** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252

**Comment by VictorPhilipp** [comment]
I merged krzychu124's change into this version
