### ISSUE TITLE
Cars disappearing after road/rails chaning

### ISSUE THREAD

**Issue by Mike-Sbg** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#236]
When I modify a road or a rail, every vehicle disappears at this point 

also mentioned here: https://steamcommunity.com/workshop/filedetails/discussion/583429740/1748980761804012244/

As it seems the display where you can see where routes beginn and where they end ... all routes end a the modified road/rail.

Can you please fix it ... or which informations can I provide for helping you

**Comment by aubergine10** [comment]
We're investigating this in new fork of the mod (see reference links above). If you could provide any additional infos in those links, where applicable, it would be most useful.

**Comment by VictorPhilipp** [comment]
moved
