### ISSUE TITLE
Industries DLC - Cargo planes not work

### ISSUE THREAD

**Issue by filipagh** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#237]
I try that on vanilla game with (TMPE)

cargo airport / airport hub - any i/o traffic (planes trains cars)
ps. service cars working with airport

**Comment by aubergine10** [comment]
A fork of the mod fixes this bug: https://steamcommunity.com/sharedfiles/filedetails/?id=1637663252

**Comment by filipagh** [comment]
@aubergine10 thanks I did it yesterday :)

**Comment by aubergine10** [comment]
If it's working please close issue

**Comment by filipagh** [comment]
its issue of this version, but its dead end so
