### ISSUE TITLE
Enable train to use multiplatform and multi-track station

### ISSUE THREAD

**Issue by aditya-murda** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#245]
On multi-platform stations, trains will always choose the leftmost or outermost platform. On a dense rail network, this causes train congestion. On another occasion, multi-platform cargo trains that connected to several rail networks can only spawn trains in default platform (e.g. the outermost platform). For better platform usage, the train pathfinding should be able to use all platform stations and all tracks

**Comment by originalfoo** [comment]
I'm going to move this over to the new issue tracker and will update with new URL.

**Comment by originalfoo** [comment]
Continued here: https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/issues/265
