### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by ghoba82** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#248]
how to install it without steam

**Comment by originalfoo** [comment]
You can find zip files of latest TM:PE releases here (current Stable version is 10.18, current Labs version is 10.19):
https://github.com/krzychu124/Cities-Skylines-Traffic-Manager-President-Edition/releases

Unzip the files in to your local mods folder (google to find details of where that is on various operating systems).
