### ISSUE TITLE
Advanced Parking AI

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#29]
Cars are able to look for alternative parking spots in a broader vicinity.
Feature must be coordinated with RushHour mod: Improved parking AI of RushHour has to be disabled if Advanced Parking AI is activated.

**Comment by VictorPhilipp** [comment]
Works together with https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/issues/18

**Comment by DaEgi01** [comment]
What I don't like about the RushHour implementation is that cars will drive directly to the parking spot, ignoring roads and buildings.
That kind of sucks so I have disabled that feature in RushHour although I like the idea very much.
I hope that your implementation will be better :)

**Comment by VictorPhilipp** [comment]
Yes, car are ordinarily driving to the the parking lot. Only on the very last part (sidewalk -> parking space location) they are "floating".

**Comment by VictorPhilipp** [comment]
Done in 1.8.0
