### ISSUE TITLE
"Green arrow" at timed traffic light junctions

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#31]
@patrickjpeterson

https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Gr%C3%BCner_Pfeil.jpg/220px-Gr%C3%BCner_Pfeil.jpg

**Comment by VictorPhilipp** [comment]
http://steamcommunity.com/workshop/filedetails/discussion/583429740/1470840994968932782/

**Comment by DaEgi01** [comment]
We can already to that manually by separating right turn lights and make them always green.
In my eyes it should not be not be a "separate feature", maybe just a convenience function, to speed up the setup.

**Comment by adiac** [comment]
Not quite. The green arrow is like a Stop sign for right turns. You habe to stop first, then obey yield rules and only then you are allowed to turn right at a red traffic light.

**Comment by VictorPhilipp** [comment]
moved
