### ISSUE TITLE
Make left turning vehicles at (timed) traffic lights wait for oncoming traffic

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#32]
@patrickjpeterson

Should be configurable.

**Comment by CRCinAU** [comment]
Would I be right in thinking this translates to right turning vehicles giving way on left hand drive maps?

If so, that'd be awesome :)

**Comment by StrangerCoug** [comment]
This looks similar to a feature suggestion I made on the page for the mod itself last week: allowing a protected/permissive mode for turns. If you need ideas for the UI, the trend in American traffic lights is to use _two_ yellow arrows: the normal yellow arrow that's steady, and a flashing yellow arrow that does what you describe. [Here's one video describing how such a traffic light works.](https://www.youtube.com/watch?v=pU8ThDYZcCc)

**Comment by VictorPhilipp** [comment]
A new request containing a perfect summation of the problems involved in realizing this feature:

http://steamcommunity.com/workshop/filedetails/discussion/583429740/1290690669222931967/

**Comment by Dezelles** [comment]
I'm not sure if that's all there is to it, but would it not be possible for the vehicles to also be able to turn to a building on the opposite side of the road? 
For me, the idea is the same: vehicles can cross an opposite path if and only if the traffic in that opposite route is "null". 
The essential difference is that in the first case, there are nodes, not in the second... 
In the second case, the player could use "artificial nodes" but it seems to me that there would still be a problem: I don't have impression that vehicles use these nodes to turn around and reach the target building (even using a lane connector...). I don't know if it's a construction problem (position of the artificial node in relation to the building), a configuration problem (the need to allow the U-turn at intersections and/or the absence of a directional arrow) or a  general AI problem that doesn't allow this type of maneuver.

**Comment by VictorPhilipp** [comment]
@Dezelles You are right, turning to reach a building is a completely different game mechanism which cannot be simply covered by the current priority rules implementation. However, I will look into the topic after the release of version 1.10. Maybe I can come up with a simple solution for it.
