### ISSUE TITLE
Add dedicated semaphore for U-turn.

### ISSUE THREAD

**Issue by mpuheim** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#37]
It would be useful in some junctions to be able  to change mode to four semaphores:
right-hand traffic: u-turn, left, forward, right
left-hand traffic: left, forward, right, u-turn

**Comment by VictorPhilipp** [comment]
U-turns are currently handled by the left/right-turn traffic light. Why would you need another traffic light for u-turns?
