### ISSUE TITLE
[GER] Vorschläge / Ideen für den Traffic Manager Mod

### ISSUE THREAD

**Issue by Vitalis2166** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#39]
Erstmal ein Hallo an die Community und Victor.

Mein Name ist Tommi und ich bin leidenschaftlicher Cities Spieler erster Stunde. Arbeite mit der Traffic Mod sehr Intensive, und von daher fallen mir hier und da immer mal wieder sachen ein die man einbauen könnte.

Ps: Die links funktionieren nur wenn man sie in die URL kopiert ...

Idee Nr.: 1:

Wer kennt diese Schilder nicht [https://goo.gl/UUF0BC](url) . Meine Idee wäre solche Schilder einzubauen, um auf viel befahrenden Straßen von LKWs entwas ruhe einkehren zu lassen.

Ich weiß leider nur nicht ob von Autos viel Lärm ausgeht und sich dies lohnt.

Idee Nr.: 2:

Eine Copy/ pase sowie eine Preset Funktion für den Linienverbinder einzubauen.

und zu guter letzt...

Idee Nr.: 3:

Eine Stay in Line [https://goo.gl/Tri1SY](url) Funktion mit einzubauen.
Zugegeben diesen Effekt lässt sich auch mit den Linienverbinder ermöglichen, ist aber etwas fummelig wenn man fünf bis zehn Note Points durchgehen muss. Da fällt mir gerade beim Schreiben ein, wenn die oben genante Funktion eingebaut ist mit Preset und Copy/ pase, bräuchte man dies auch nicht mehr.

Hiermit wünsche ich euch ein schönen Abend und eine schöne Weihnachtszeit.
 
Gruß
Tommi

Ps: Die links funktionieren nur wenn man sie in die URL kopiert ...

**Comment by DaEgi01** [comment]
Hallo Vitalis2166,
zur Idee Nr. 1 gibt es bereits mit TM:PE die Möglichkeit, die Geschwindigkeit auf jedem beliebigen Straßensegment auf 30km/h zu beschränken und LKWs die durchfahrt zu verweigert.
Es gibt zwar keine schönen Schilder, aber der Effekt ist dennoch da.
Idee Nr. 2 find ich an sich ganz nett, allerdings gibt es so viele unterschiedliche Kreuzungen, ich weiß nicht ob das letztendlich so sinnvoll wäre. Ich wäre glaub in den meisten Fällen länger damit beschäftigt die passende Konfiguration rauszusuchen, als es manuell nochmal zu machen.
Aber klar, wenn man so ein paar Standardkonfigurationen hat und die öfter nutzen möchte ist das schon sehr sinnvoll.
Idee Nr. 3 find ich auch ganz nett. Auch wenn ich ehrlich gesagt noch nie ein Problem damit hatte, dass die Autos die Spur wechseln können, sondern bisher immer nur das gegenteilige Problem, das nicht genug Nodes da waren, damit sie es tun konnten.
Ggf. könnte man das Icon mit dem man bei Kreuzungen den Spurwechsel anmachen kann auf alle Segmente ausweiten, wobei es bei regulären Segmenten halt als Standard aktiv ist..... ist das nicht sogar schon so? XD .. kann grad nicht ins game.

**Comment by Vitalis2166** [comment]
Hallo DaEgi01,

Ich glaube du hast die erste Idee nicht ganz verstanden. ich meinte, dass man Autos / LKW zu nacht zeiten langsamer fahren lässt als Tagsüber also Nacht 30 Km/h und am tag das reguläre Tempo. Ich meinte nicht es Komplett zu verbieten, die Option kennt ich.

**Comment by VictorPhilipp** [comment]
"Stay in Lane" ist jetzt drin:
1. "Fahrspurverbinder" (eng: "Lane connector") aufrufen
2. Kreuzung auswählen
3. Umschalt + S drücken (mehrmals drücken, um "stay on line" nur für bestimmte Richtungen zu aktivieren).

**Comment by DaEgi01** [comment]
Hallo Vatalis2166,

du hast recht, ich habe deine erste Idee falsch verstanden gehabt.
So finde ich sie sehr gut. 
Leider hat Lärm nicht soviel Einfluss auf den Grundstückswert, aber das könnte man ja mit einer anderen Mod ändern ;)

Gruß

**Comment by VictorPhilipp** [comment]
Deine erste Idee geht extrem ins Micromanagement. Ich weiß nicht, ob die Userbasis, die so ein Feature benutzen würde, ausreichend groß wäre. Wenn man die Idee weiterspinnt, könnte man insgesamt überlegen, die Features
- Fahrzeugbeschränkungen
- Geschwindigkeitsbegrenzungen und
- zeitgesteuerte Ampelschaltungen
zumindest für jede Tageszeit (Tag/Nacht) separat (und zusätzlich global) konfigurierbar zu machen. Noch ein Schritt weiter und wir landen bei stundenweisen Tempolimits, Durchfahrverboten, etc.

**Comment by VictorPhilipp** [comment]
Das Copy/Paste-Feature samt Möglichkeit, Konfigurationsvorlagen (Presets) für Kreuzungen zu erstellen, werde ich als Nächstes bearbeiten.
So wie ich es sehe, sollten Spieler dann sämtliche kreuzungsbezogenen Einstellungen auf andere Kreuzungen übertragen können, d.h.:
- zeitgesteuerte Ampelschaltungen
- Richtungspfeile
- verbundene Spuren
- Kreuzungsbeschränkungen

Ein offene Frage hierbei ist noch, wie man mit unterschiedlichen Kreuzungen umgeht: Kopiere ich z.B. die Einstellungen von einer 4er-Krezugung, an der zwei 6-spurige Straßen und zwei 4-spurige Straßen aufeinander treffen auf einer simplere Kreuzgung (z.B. 4 x zwei-spurige Straßen), muss ein Algorithmus entscheiden, wie er z.B. die verbunden Fahrspuren und Richtungspfeile übernimmt.

Außerdem müssen die Kreuzungseinstellungen "drehbar" gemacht werden. Möchte man z.B. eine Ampel, bei der eine Richtung eine besonders lange Grünphase hat auf eine andere Kreuzung kopieren, weiß das System ja erstmal nicht, welche Straße die längere Grünphase erhalten soll. Man benötigt also im Userinterface Buttons, um die Ampel um jeweils eine Straße nach links oder rechts zu drehen.

**Comment by Bahnbekloppter** [comment]
Moin! 
Ich hänge mich hier mal an. :)
Vermutlich gehöre ich schon in die Kategorie "Hardcore-Nutzer" bezüglich des TM:PE! :D 
Ich finde die Mod und die Entwicklung in der Vergangenheit großartig und ohne die Mod weiß ich nicht, ob ich überhaupt noch C:S spielen würde!

Ich hätte da zwei Ideen:

1. Manueller Betrieb auch bei zeitgesteuerten Ampeln
 Ich stelle mir das so vor, dass die programmierte Ampel für die Zeit der manuellen Kontrolle "vergessen" wird. Sobald ich die Manuelle Steuerung verlasse, ist alles wie vorher. 
2. Logische Verknüpfung von Ampelsteuerungen 
 Das wäre schon eine komplexere und speziellere Sache. Vielleicht irgendetwas in die Richtung Wenn-dies-dann-das. Dann könnte man z.B. eine bestimmte Ampelphase aufrufen bzw. weiterspringen, wenn bei der Nachbar-Kreuzung eine Ampel auf Rot oder Grün springt. Problematisch stelle ich mir dabei aber die Zuordnung vor. 

Andere Wünsche wie Grüner Pfeil, Vorfahrtsbeschilderung bei Ampelkreuzungen (für Linksabbieger z.B.) und Ähnliches wurden ja bereits geäußert und ich würde diese sehr begrüßen! :)

Viele Grüße
Daniel

**Comment by Vitalis2166** [comment]
Ho Ho Ho,

@ Victor, ja Dies muss dann getrennt werden mit den Presets zb. einer 4er Krezung auf 6er zu kopieren sollte dann nicht möglich sein, oder aber (Mikromanagement) es werden gewisse standarts Kopiert, Abb. 1 https://drive.google.com/file/d/0BwuUrreb8JuxYUExZG0xeFlsNlk/view?usp=sharing , dies bedeutet, dass er es automatisch erkennt und wie in Abb. 1 zu sehen es Intelligent gesplittet wird. oh Gott der Victor killt mich jetzt :) sorry. Das jetzt mit den Stay in line wäre das non plus Ultra , ich habs mal in die Grafik mit eingebaut jedoch kann man dies auch Manuell machen wie man es brauchst. Danke nochmal Victor dass mir das Stay in Line Vereinfacht hast geile sache, ich bin echt ein fan, kann ich auch jedem empfehlen. 

- Kreuzungseinstellungen "drehbar"

Du meinst warscheinlich wie in einem Bildbearbeitungsprogramm Bild drehen 90 Grad im Uhrzeigersinn. Das stimmt, ja ich merke auch gerade das geht auch doll ins detail. Okay verwerfen wir erstmal die 1. Idee und konzentrieren uns auf Copy / pase...

------------------------------

Also... Du hattest vor Presets für Fahrspurenverbinder und Presets für Ampeln zu machen, wenn ich das jetzt richtig verstanden hab.

**- Preset Fahrspurenverbinder** 

ich fantasiere jetzt einfach mal, ich stell mir das so vor, das es ein fenster gibt wo folgende Button zur Auswahl gibt, Preset Speichern, Preset Löschen, Preset Kopieren, dass sieht dann wie folgt aus Abb. 2 https://drive.google.com/file/d/0BwuUrreb8Juxc1FoMWdjOU5Da2s/view?usp=sharing   , man könnte auch die Button Speichern, löschen und Kopieren auf die button setzten was ich rot durchgestrichen habe, somit bleiben die anklickbaren Button für die Presets selber frei und könnte die erstellten Presets anklicken zum kopieren. ich hoffe das war verständlich ausgedrückt,also im Endeffekt müsste es so gemacht sein, dass man erstellte presets auch anklicken kann. Das wärs eigentlich schon, dann ist jedoch zu beachten ob man eine Kreuzung oder ein Straßenabschnitt ohne Kreuzung erstellt wird. Entweder wird dies gelöst in dem man in der PresetListe (die unten zu sehen auf Abb. 2) Kategorien einbaut werden wie 2 way Cross, 4 way cross und so weiter,... oder beim erstellen des Presets erkennt er automatisch um was für ein Notepunkt es sich handelt und Klassifiziert dies automatisch.

Ich bedanke mich und wünsche frohes Fest an alle.

Gruß
Tommiundso // Vitalis

**Comment by Vitalis2166** [comment]
Hallo Bahnbekloppter,

deiner Ersten Idee kann ich nicht ganz folgen. Sorry bitte nochmal ausführlicher...

Idee 2. ich weiß dein ansatz aber ich bin mir nicht sicher ob man benachbarte Ampelt verknüpfen kann so das sie Automatisch eine Intelligente Schaltung vornehmen dies ist ja bereits in der Einstellung der Zeit gesteuerten Ampeln vorhanden, jedoch müsste diese Intelligenz auf Benachbarte ampeln überspringen, und auch da den Algorithmus (deine angemerkte Zuordnung) ändern wär eine Revolution in der Ampel Technik, aber dafällt mir noch was ein hab da schon ein Ansatz aber das geh ich mir nochmal durch den kopf gehen. Evtl. geht das auch schon so, aber das wäre mega fummel arbeit.

Aber immerhin gibt es Grüne wellen, nur das noch weiter ausgebaut oha, der Victor sagt Danke :)

Ich bin aber an einer Lösung, dein Vorschlag Bahnbekloppter, ist echt nicht schlecht, werde sie dann Präsentieren, sodass der Herr Victor es Umsetzen kann :P jetzt HASST er mich :)

**Comment by Vitalis2166** [comment]
Hallo,

nochmal was GANZ anders, ich zeig euch erstmal was ich entdeckt habe und dann kommt meine Intention auf dies Video: https://www.youtube.com/watch?v=gonTG5ZQlfE

 **Man sieht sehr schon wie sie von einer Fahrbahn auf die gegenüberliegende Fahrbahn Geleitet werden.**

dies kann unterschiedlich ausfallen:
http://www.dewberry.com/images/default-source/blog-images/cfi_intersection_02.jpg?sfvrsn=4

http://img.ksl.com/slc/221/22173/2217316.jpg

**am besten mal dies video schauen:**
https://www.youtube.com/watch?v=_dB25GPPdeU&t=57s


Dies ist mein Erster Versuch:
https://drive.google.com/file/d/0BwuUrreb8JuxS1d1Z1VwM0ZtQWc/view?usp=sharing

Dies wäre sehr nett, denn gerade Kreuzungen wie im gezeigtem Video sind perfekt für eine Großstadt / oder als zentraler punkt möglich in Verbindung mit Perfekten angelegten Anschlüssen wie zb. Malteser Autobahnkreuzungen (https://drive.google.com/file/d/0BwuUrreb8Juxb0tieW5IcGtOZkk/view?usp=sharing)
