### ISSUE TITLE
Fixed: Some citizens are using evacuation route buses like a regular bus line

### ISSUE THREAD

**Issue by DaEgi01** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#40]
Hey,
does the new patch 1.6.1-f2 makes this option obsolete?
"New option: Evacuation busses may ignore traffic rules (Natural Disasters DLC required)".
Thanks for implementing it though :)

**Comment by VictorPhilipp** [comment]
As I read in the changelog the "bug" was fixed by CO! But honestly I haven't tested it. ;-)
