### ISSUE TITLE
When some road has both pedestrian and bicycle lanes cars should prefer bicycle lanes

### ISSUE THREAD

**Issue by earalov** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#46]
That looks weird: empty bicycle lanes and busy pedestrian lanes:
http://i.imgur.com/joxgjdi.jpg

**Comment by appinteractive** [comment]
Found it also strange that the cars was running on the pedestrian lanes.

**Comment by VictorPhilipp** [comment]
This change has to be made by the authors of NeXT2 - they would have to move the car lanes onto the bicycle lanes.
