### ISSUE TITLE
No U-turns anymore

### ISSUE THREAD

**Issue by dymanoid** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#49]
My TE:PE 1.8.16 is configured so that the U-turns are generally enabled. The Advanced AI is enabled too.
Recently I noticed that my traffic doesn't make any U-turns anymore. For example, the bus lines are drawn using the U-turns, but in fact all the buses search their way in a "standard" C:S way.

Here is a screenshot:

![20170422163140_1](https://cloud.githubusercontent.com/assets/9433345/25307199/fb8bee46-279c-11e7-8349-191818c8f57d.jpg)

And the logs:
[output_log.txt](https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/files/949205/output_log.txt)

[TMPE.log.txt](https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/files/949206/TMPE.log.txt)

**Comment by blovemaple** [comment]
I have this problem too, and bus lines are also not drawn using u-turns.

**Comment by dymanoid** [comment]
For testing, I reverted the changes from the commit 48810a460f9de8394aec6f17170f41de2308a5f0. The buses now make they U-turns. So probably these changes have to be revised...

**Comment by VictorPhilipp** [comment]
Fixed and updated right now!
