### ISSUE TITLE
Bug when intersection without pedestrian crossing

### ISSUE THREAD

**Issue by thibaultmol** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#5]
Hi,

I have a save where I have multiple crossings where the lights for the pedestrians never go green. I want them to use the pedestrian bridge. But they still seem to be queuing for it. Is this a bug?
Windows 10 64-bit, CS: 1.4
And I also have Traffic++ V2 installed
all my subs from workshop: http://steamcommunity.com/id/thibaultmol/myworkshopfiles/?browsesort=mysubscriptions&browsefilter=mysubscriptions&p=1
Link to save file: https://drive.google.com/file/d/0B0rhFYAkXDVJUHd6b01TLVdrM1k/view?usp=sharing

Thanks

**Comment by thibaultmol** [comment]
Btw, the region where the problem is occurring is in the 'industrial' district at the bottom right corner.

**Comment by VictorPhilipp** [comment]
Will be implemented in version 1.7.0!
