### ISSUE TITLE
Single cars / trains get stuck forever

### ISSUE THREAD

**Issue by cmfcmf** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#50]
Sometimes, for no apparent reason, a single car or train gets stuck forever. This causes major traffic jams and brings the city to a halt. I'd very much appreciate having some way to despawn just the car / train causing the problems. Here is an example of such a situation. The car in the blue circle is stuck. It's destination is the building to the right of it (opposite to the one demanding for police). Maybe something is wrong with the advanced parking AI?

![image](https://cloud.githubusercontent.com/assets/2145092/25356207/b3242684-2939-11e7-8060-520cf8ca531c.png)

Pressing the reset stuck vehicles / cims button doesn't help.

I've enabled all features, very high simulation accuracy, all improved KI options + parking KI, as well as realistic speeds.

Let me know if there is more I can do to help!

**Comment by VictorPhilipp** [comment]
Yes, I noticed this as well. However it is really hard to find out what is going wrong. After the Mass Transit DLC is released I will get on that!

**Comment by VictorPhilipp** [comment]
I think I identified the bug. Should be fixed in version 1.9.0 (coming out on Thursday).

**Comment by cmfcmf** [comment]
Great, thank you! 
I'll test and report once the new version is out.

**Comment by VictorPhilipp** [comment]
Fixed and updated right now!

**Comment by cmfcmf** [comment]
> Fixed and updated right now!

Tested things a bit - so far, so good! 👍
