### ISSUE TITLE
Modularize TM:PE such that individual features are available as workshop items

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#58]
Players could choose between individual features by subscribing to the respective workshop items. As a side effect, this would minimize impact on performance since unused features would not need to run along with the game.

**Comment by DaEgi01** [comment]
mmmmh ... not sure if that is a good idea ;D

**Comment by VictorPhilipp** [comment]
moved
