### ISSUE TITLE
Powerful lane changer as in Traffic++

### ISSUE THREAD

**Issue by DaEgi01** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#6]
It would be nice to have a powerful "drag & drop" lane connector as in Traffic++.
There are certain situations where a manual lane changer is very powerful and cannot be replaced with an automatic solution.

> TM:PE integrates an improved lane selection algorithm. Normally, there is no need to manually define lane changing policies since the system is designed to let vehicles automatically choose the "best" path in terms of traffic density & speed**. Additionally, you can enable the highway rule system to implement a fully-automatic, real-life based set of lane splitting/merging rules on highways. If enabled, entry and exit lanes on highways are automatically detected and vehicles behave according to these rules (read the manual for further explanation). 

The highway rule system is very well done! But I want to have something similar for inner town/city traffic. Since inner town traffic can get much more complicated, with 6-way intersections, various merging and splitting scenarios, an automatic solution just can't get player's  intention in every case.

One improvement to the T++ lane connector would be to pre-connect every lane with the default connection.

> A manual lane-changer (like in T++) would interfere with TM:PE's AI. That means that a long test run is necessary in order to guarantee correct behaviour of both the AI and the lane changer (I am currently quite busy with my studies - I am currently finishing my final thesis and this requires a lot of time).

Implement it as an experimental option that can be disabled and let the community test it. 
I bet that a lot of people are willing to test it and give feedback. I am definitely in.

**Comment by VictorPhilipp** [comment]
Will be implemented in version 1.7.0!

**Comment by DaEgi01** [comment]
Thank you!! Looks great.
