### ISSUE TITLE
Split out delivery vans, cargo trucks, and tractors

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#63]
"I love the vehicle restrictions.. But it would be beneficial to allow commercial deliveries and still block tractors and / or industrial cargo trucks."

see http://steamcommunity.com/workshop/filedetails/discussion/583429740/1318835718951055747/

**Comment by Dezelles** [comment]
Could we add the bike's circulation on the lanes of cars? It would be more realistic and especially useful with the "Bike Ban On Sidewalks".
In theory, could we also add trams to the list of selectable vehicles? I know this would pose a visual problem in which you don't wish to interfere: therefore, it is only a theoretical question.

**Comment by Dezelles** [comment]
Precision on the circulation of bicycles on roadways: the road editor made it possible with a lane "mixed". However, the result does not seem satisfactory: circulations are not synchronized and bicycles and cars overlap.

**Comment by VictorPhilipp** [comment]
The ability to have mixed lanes (e.g. for bicycles and cars) would have to be implemented by CO, not by TMPE.

**Comment by VictorPhilipp** [comment]
moved
