### ISSUE TITLE
Highway AI - problems with on ramps close to off ramps.

### ISSUE THREAD

**Issue by CRCinAU** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#7]
If you have the highway logic turned on, and have an on ramp closely followed by an off ramp, vehicles that enter the highway on the onramp will *always* follow the off ramp.

This seems to be because a vehicle can't go straight ahead on the exit lane to the off ramp.

This means some vehicles are forced to take considerable detours instead of just continuing on their way.

**Comment by VictorPhilipp** [comment]
This cannot be changed since its game-internal. Vehicles may only change lanes at so-called nodes (you can see all nodes by enabling the "Nodes and segments" overlay in TMPE's options dialog.

**Comment by VictorPhilipp** [comment]
So, you mean without the highway rule system, they are able to change lanes? This could be an issue ;-)

**Comment by VictorPhilipp** [comment]
I checked the code. I do not think that this is a bug. Highway rules are more strict than the game's default rules. Vehicles that enter a highway are not allowed to switch lanes immediately. They have to wait for a lane changing point (node). If you build entries and exists too close together there is no such lane changing point. Thus, vehicles cannot really enter the highway at this point. While using highway rules, try to reserve enough space at those points.
