### ISSUE TITLE
Timed traffic lights do not correctly recognize set vehicle restrictions

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#71]
http://imgur.com/a/GMZi6
@alborzka

**Comment by Bahnbekloppter** [comment]
A workaround for this is to turn the direction of the road-segments. Turning the road  to an one-way-street temporary, change the direction to make this street outgoing from the crossing and change the type of the street back to your originally street. 
This Bug only appears on the oncoming part of an street.

**Comment by VictorPhilipp** [comment]
Yes, changing direction forces TM:PE to remove the underlying custom traffic light from the junction.
Fixed in v1.10.2.
