### ISSUE TITLE
Configurable service vehicle selection based on distance

### ISSUE THREAD

**Issue by VictorPhilipp** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#79]
@TWarrior says: "please fix the broken randomized assigning of emergency vehicles, hearses etc to buildings and switch it to a proximity based system."

There are mods that increase the effect of distance on service vehicle selection but they are incompatible with TMPE because both mods touch the same code.

**Comment by DaEgi01** [comment]
it would be great if there would be no code for that at all in TM:PE.
or is it necessary for some reason?

**Comment by VictorPhilipp** [comment]
@DaEgi01 I have found your mod "Service Radius Adjuster" in the workshop. If I am not mistaken, it already covers what this issue is about, right? :-)

**Comment by DaEgi01** [comment]
@VictorPhilipp my mod only covers the effect radius of the buildings, and thus only affects the land value.
but there is another mod, that uses that value to distribute service based vehicles via different strategies you can configure. there is also a proximity based system included. https://steamcommunity.com/sharedfiles/filedetails/?id=512341354
it would be awesome if these three mods would work flawlessly together.

**Comment by VictorPhilipp** [comment]
Since Central Service Dispatcher should be 100% compatible with TM:PE, I am closing this issue.
