### ISSUE TITLE
Highway AI - 3 lane highway roundabouts have exits from the inner lane.

### ISSUE THREAD

**Issue by CRCinAU** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#8]
When placing a large roundabout, the default makeup is 3 lane highway.

When adding on ramps / off ramps in a square configuration, the 'exit' lane is shown as the inner most lane - meaning exiting traffic has to cross all 3 lanes to exit the roundabout.

Can supply a screenshot of this if required.

**Comment by VictorPhilipp** [comment]
A screenshot would be very helpful to recreate this.

**Comment by CRCinAU** [comment]
Sure - I'm not on a system with C:S installed now, so I'll get something to you tomorrow. I started typing then realised I had no way of actually describing the roundabout in question...

**Comment by CRCinAU** [comment]
Played a bit with my roundabouts today... Attaching screenshot...
![20160714212802_1](https://cloud.githubusercontent.com/assets/3992884/16837942/df223d44-4a09-11e6-8383-cdcd03acd3d9.jpg)

**Comment by CRCinAU** [comment]
![20160714212934_1](https://cloud.githubusercontent.com/assets/3992884/16837982/17816606-4a0a-11e6-9604-11635a747133.jpg)
![20160714213018_1](https://cloud.githubusercontent.com/assets/3992884/16837995/2fc30f44-4a0a-11e6-9399-464d5dc2ba27.jpg)

**Comment by CRCinAU** [comment]
![20160714213145_1](https://cloud.githubusercontent.com/assets/3992884/16838018/627e022c-4a0a-11e6-9e9e-2b866af9c1ce.jpg)

**Comment by CRCinAU** [comment]
It also seems to lead to issues like this:
![20160714213652_1](https://cloud.githubusercontent.com/assets/3992884/16838153/23ee9520-4a0b-11e6-97d7-ef3c96c96772.jpg)

**Comment by CRCinAU** [comment]
This is the same roundabout with 3 lane one way street (with speed limit raised) as an alternative:
![20160714213922_1](https://cloud.githubusercontent.com/assets/3992884/16838228/82de7e60-4a0b-11e6-8926-cde62f9920a1.jpg)

**Comment by VictorPhilipp** [comment]
I confirm this to be a bug. At this kind of complex junction, highway rules should be completely disabled. This circumstance is not detected.

**Comment by VictorPhilipp** [comment]
Fixed
