### ISSUE TITLE
minimum green-time on traffic lights / demand phase

### ISSUE THREAD

**Issue by Bahnbekloppter** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#82]
Very often i use 0 seconds minimum green-time on traffic lights, to skip an phase when it's not needed. 
But sometimes, the green-time is only 1 oder 2 seconds.
Is it possible to declare a phase as "demand phase" or something similar to uncuple it from the minimum-green time?

**Comment by VictorPhilipp** [comment]
How is a "demand phase" different from setting minimum time to 0?
