### ISSUE TITLE
mistakes in Simplified Chinese translation

### ISSUE THREAD

**Issue by Emphasia** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#83]
Did some corrections on the original version.
[TMPE.txt](https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/files/1291984/TMPE.txt)

**Comment by Emphasia** [comment]
The above corrected translation is based on 874913f85, and then it was changed in f3df93450ec, (and if that was the same author as all the previous translation, then he changed his signature in f3df93450ec, and 92bd41a01 changed it back.😂).
By the way, the tutorials seems haven't been translated yet? If that's OK, I'd like to take this assignment (though it might take a few days because of my final exam...).

**Comment by VictorPhilipp** [comment]
First of all, thank you for the translation! I copied some of the modified texts into the Google translator and was really surprised that the original author put so much advertisment into it.

Having a translated tutorial would be nice but there's no hurry. I wish you much success with your final exam!
