### ISSUE TITLE
Feature Request: Hold [ALT;CTRL;SHIFT;whatever] during street/crossing creation to disable left turn

### ISSUE THREAD

**Issue by blackliner** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#84]
Hi there,

awesome mod, i mainly use it's arrow tool to disallow left turns on highway mergers. I think it would be an awesome addition to have that feature on a (configurable) hotkey. 

What do you guys think?

PS: Sorry, I am not (yet) able to provide a PR. Although i do have modding expirience with unity (Kerbal Space Program), i never did a C:S mod.

**Comment by rafamariofan** [comment]
+1 Here in Brazil you can't turn left at almost every junction with traffic lights.

**Comment by aubergine10** [comment]
Would this be better as a mod option instead of modifying the build tool?

So you could default all new junctions to prevent left or right turn (depending on game RHD or LHD setting), with the option to override on junction-by-junction basis using the lane connector or lane arrow tools...?

**Comment by VictorPhilipp** [comment]
moved
