### ISSUE TITLE
Update repo to 1.10.4

### ISSUE THREAD

**Issue by lediur** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#86]
With the new changes brought about in Cities Skylines 1.9.0, I'd be very interested in seeing what modifications you had to make to fix any compatibility issues with TM:PE.

The repository seems to contain the older version updated back in August (1.10.3). Would it be possible to push your latest changes to GitHub? 

Thanks for your incredible work putting this mod together.

**Comment by VictorPhilipp** [comment]
Thanks for reminding me - I forgot to push the latest version to GitHub. I have updated the repo.
