### ISSUE TITLE
DivideByZeroException for roads with default speed less than 6.25 km/h

### ISSUE THREAD

**Issue by penma** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#87]
Placing a road that has a default speed limit of less than 6.25 km/h (or 0.125 as set in the road editor) (will call it "bugroad" from now on) causes a DivideByZeroException as soon as a vehicle starts driving over it. It might be the case that advanced AI + DLS has to be enabled for this, but I'm not exactly sure.

Originally encountered with https://steamcommunity.com/sharedfiles/filedetails/?id=1175300283 which sets a value of 0.1 (5 km/h) but any other bugroad will do. Quickly made two roads in asset editor, lane speed 0.124 throws exceptions, 0.126 works fine.

Crash happens in TrafficMeasurementManager.CalcLaneRelativeMeanSpeed. laneVehicleSpeedLimit is zero because GetLockFreeGameSpeedLimit(...) * 8 is less than 1 for such bugroads, causing div0 in the next line.

Suggested solution: set laneVehicleSpeedLimit to at least 1 before doing anything with it.

**Comment by VictorPhilipp** [comment]
Thanks for the report! It will be fixed with the next update. https://github.com/VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition/tree/1.10.5
