### ISSUE TITLE
Lane changer makes all vehicles despawn

### ISSUE THREAD

**Issue by skerit** [VictorPhilipp/Cities-Skylines-Traffic-Manager-President-Edition#92]
At the bottom you see 2 lane connectors, in pink & green. Vehicles driving on that road just despawn, they never go where I want them to go. Why is that?

![schermafdruk van 2017-12-26 21-44-54](https://user-images.githubusercontent.com/755212/34364416-26faf818-ea86-11e7-8abf-5b164b7bcf2d.png)

**Comment by krzychu124** [comment]
Hi, 
I can't see here where green & violet lane goes, but it seems like vehicles heading that lane previously didn't recalculated their paths after lane connection modifications and from this point they can't change direction to go to their destination - one-way lanes. In this case they have to be despawned to restart pathfinding calculations.

**Comment by skerit** [comment]
@krzychu124 Aha, that kind of explains it. I noticed some other lane changes seemed to affect the chosen paths immediately, but after a while this one too did seem to work again.
